////////////////////////////////////////////////////////////////////////
//
// jbpm3processdocgpd_typeinfo.java
//
// This file was generated by XMLSpy 2009sp1 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//
////////////////////////////////////////////////////////////////////////


package com.jbpm3processdocgpd;

import com.migration.typeinfo.*;



public class jbpm3processdocgpd_TypeInfo
{
	// namespaces indices
	public static final int _altova_ni = 0;
	public static final int _altova_ni_xs = 1;


	// typeinfo indices
	public static final int _altova_tif = 0 ;
	public static final int _altova_ti_altova_jbpm3processdocgpd2 = _altova_tif ;
	public static final int _altova_ti_altova_bendpointType = 1 ;
	public static final int _altova_ti_altova_w2Type = 2 ;
	public static final int _altova_ti_altova_w1Type = 3 ;
	public static final int _altova_ti_altova_h2Type = 4 ;
	public static final int _altova_ti_altova_h1Type = 5 ;
	public static final int _altova_ti_altova_edgeType = 6 ;
	public static final int _altova_ti_altova_labelType = 7 ;
	public static final int _altova_ti_altova_nodeType = 8 ;
	public static final int _altova_ti_altova_yType = 9 ;
	public static final int _altova_ti_altova_xType = 10 ;
	public static final int _altova_ti_altova_widthType = 11 ;
	public static final int _altova_ti_altova_heightType = 12 ;
	public static final int _altova_ti_altova_root_containerType = 13 ;
	public static final int _altova_ti_altova_widthType2 = 14 ;
	public static final int _altova_ti_altova_nameType = 15 ;
	public static final int _altova_ti_altova_heightType2 = 16 ;
	public static final int _altova_ti_altova_yType2 = 17 ;
	public static final int _altova_ti_altova_xType2 = 18 ;
	public static final int _altova_til = 19 ;

	public static final int _altova_tif_xs = _altova_til;
	public static final int _altova_ti_xs_altova_ENTITIES = _altova_tif_xs ;
	public static final int _altova_ti_xs_altova_ENTITY = 20 ;
	public static final int _altova_ti_xs_altova_ID = 21 ;
	public static final int _altova_ti_xs_altova_IDREF = 22 ;
	public static final int _altova_ti_xs_altova_IDREFS = 23 ;
	public static final int _altova_ti_xs_altova_NCName = 24 ;
	public static final int _altova_ti_xs_altova_NMTOKEN = 25 ;
	public static final int _altova_ti_xs_altova_NMTOKENS = 26 ;
	public static final int _altova_ti_xs_altova_NOTATION = 27 ;
	public static final int _altova_ti_xs_altova_Name = 28 ;
	public static final int _altova_ti_xs_altova_QName = 29 ;
	public static final int _altova_ti_xs_altova_anySimpleType = 30 ;
	public static final int _altova_ti_xs_altova_anyType = 31 ;
	public static final int _altova_ti_xs_altova_anyURI = 32 ;
	public static final int _altova_ti_xs_altova_base64Binary = 33 ;
	public static final int _altova_ti_xs_altova_boolean2 = 34 ;
	public static final int _altova_ti_xs_altova_byte2 = 35 ;
	public static final int _altova_ti_xs_altova_date = 36 ;
	public static final int _altova_ti_xs_altova_dateTime = 37 ;
	public static final int _altova_ti_xs_altova_decimal = 38 ;
	public static final int _altova_ti_xs_altova_double2 = 39 ;
	public static final int _altova_ti_xs_altova_duration = 40 ;
	public static final int _altova_ti_xs_altova_float2 = 41 ;
	public static final int _altova_ti_xs_altova_gDay = 42 ;
	public static final int _altova_ti_xs_altova_gMonth = 43 ;
	public static final int _altova_ti_xs_altova_gMonthDay = 44 ;
	public static final int _altova_ti_xs_altova_gYear = 45 ;
	public static final int _altova_ti_xs_altova_gYearMonth = 46 ;
	public static final int _altova_ti_xs_altova_hexBinary = 47 ;
	public static final int _altova_ti_xs_altova_int2 = 48 ;
	public static final int _altova_ti_xs_altova_integer = 49 ;
	public static final int _altova_ti_xs_altova_language = 50 ;
	public static final int _altova_ti_xs_altova_long2 = 51 ;
	public static final int _altova_ti_xs_altova_negativeInteger = 52 ;
	public static final int _altova_ti_xs_altova_nonNegativeInteger = 53 ;
	public static final int _altova_ti_xs_altova_nonPositiveInteger = 54 ;
	public static final int _altova_ti_xs_altova_normalizedString = 55 ;
	public static final int _altova_ti_xs_altova_positiveInteger = 56 ;
	public static final int _altova_ti_xs_altova_short2 = 57 ;
	public static final int _altova_ti_xs_altova_string2 = 58 ;
	public static final int _altova_ti_xs_altova_time = 59 ;
	public static final int _altova_ti_xs_altova_token = 60 ;
	public static final int _altova_ti_xs_altova_unsignedByte = 61 ;
	public static final int _altova_ti_xs_altova_unsignedInt = 62 ;
	public static final int _altova_ti_xs_altova_unsignedLong = 63 ;
	public static final int _altova_ti_xs_altova_unsignedShort = 64 ;
	public static final int _altova_til_xs = 65 ;



	// memberinfo indices

	public static class _altova_mi_altova_jbpm3processdocgpd2 {
		public static final int begin = 0 ;
		public static final int _bendpoint = _altova_mi_altova_jbpm3processdocgpd2.begin ;
		public static final int _edge = 1 ;
		public static final int _label = 2 ;
		public static final int _node2 = 3 ;
		public static final int _root_container = 4 ;
		public static final int end = 5 ;
	};


	public static class _altova_mi_altova_bendpointType {
		public static final int begin = _altova_mi_altova_jbpm3processdocgpd2.end ;
		public static final int _w2 = _altova_mi_altova_bendpointType.begin ;
		public static final int _w1 = 6 ;
		public static final int _h2 = 7 ;
		public static final int _h1 = 8 ;
		public static final int end = 9 ;
	};


	public static class _altova_mi_altova_w2Type {
		public static final int begin = _altova_mi_altova_bendpointType.end ;
		public static final int end = _altova_mi_altova_w2Type.begin ;
	};


	public static class _altova_mi_altova_w1Type {
		public static final int begin = _altova_mi_altova_w2Type.end ;
		public static final int end = _altova_mi_altova_w1Type.begin ;
	};


	public static class _altova_mi_altova_h2Type {
		public static final int begin = _altova_mi_altova_w1Type.end ;
		public static final int end = _altova_mi_altova_h2Type.begin ;
	};


	public static class _altova_mi_altova_h1Type {
		public static final int begin = _altova_mi_altova_h2Type.end ;
		public static final int end = _altova_mi_altova_h1Type.begin ;
	};


	public static class _altova_mi_altova_edgeType {
		public static final int begin = _altova_mi_altova_h1Type.end ;
		public static final int _label = _altova_mi_altova_edgeType.begin ;
		public static final int _bendpoint = 10 ;
		public static final int end = 11 ;
	};


	public static class _altova_mi_altova_labelType {
		public static final int begin = _altova_mi_altova_edgeType.end ;
		public static final int _y = _altova_mi_altova_labelType.begin ;
		public static final int _x = 12 ;
		public static final int end = 13 ;
	};


	public static class _altova_mi_altova_nodeType {
		public static final int begin = _altova_mi_altova_labelType.end ;
		public static final int _y = _altova_mi_altova_nodeType.begin ;
		public static final int _x = 14 ;
		public static final int _width = 15 ;
		public static final int _name = 16 ;
		public static final int _height = 17 ;
		public static final int _edge = 18 ;
		public static final int end = 19 ;
	};


	public static class _altova_mi_altova_yType {
		public static final int begin = _altova_mi_altova_nodeType.end ;
		public static final int end = _altova_mi_altova_yType.begin ;
	};


	public static class _altova_mi_altova_xType {
		public static final int begin = _altova_mi_altova_yType.end ;
		public static final int end = _altova_mi_altova_xType.begin ;
	};


	public static class _altova_mi_altova_widthType {
		public static final int begin = _altova_mi_altova_xType.end ;
		public static final int end = _altova_mi_altova_widthType.begin ;
	};


	public static class _altova_mi_altova_heightType {
		public static final int begin = _altova_mi_altova_widthType.end ;
		public static final int end = _altova_mi_altova_heightType.begin ;
	};


	public static class _altova_mi_altova_root_containerType {
		public static final int begin = _altova_mi_altova_heightType.end ;
		public static final int _width = _altova_mi_altova_root_containerType.begin ;
		public static final int _name = 20 ;
		public static final int _height = 21 ;
		public static final int _node2 = 22 ;
		public static final int end = 23 ;
	};


	public static class _altova_mi_altova_widthType2 {
		public static final int begin = _altova_mi_altova_root_containerType.end ;
		public static final int end = _altova_mi_altova_widthType2.begin ;
	};


	public static class _altova_mi_altova_nameType {
		public static final int begin = _altova_mi_altova_widthType2.end ;
		public static final int end = _altova_mi_altova_nameType.begin ;
	};


	public static class _altova_mi_altova_heightType2 {
		public static final int begin = _altova_mi_altova_nameType.end ;
		public static final int end = _altova_mi_altova_heightType2.begin ;
	};


	public static class _altova_mi_altova_yType2 {
		public static final int begin = _altova_mi_altova_heightType2.end ;
		public static final int end = _altova_mi_altova_yType2.begin ;
	};


	public static class _altova_mi_altova_xType2 {
		public static final int begin = _altova_mi_altova_yType2.end ;
		public static final int end = _altova_mi_altova_xType2.begin ;
	};


	public static class _altova_mi_xs_altova_ENTITIES {
		public static final int begin = _altova_mi_altova_xType2.end ;
		public static final int end = _altova_mi_xs_altova_ENTITIES.begin ;
	};


	public static class _altova_mi_xs_altova_ENTITY {
		public static final int begin = _altova_mi_xs_altova_ENTITIES.end ;
		public static final int end = _altova_mi_xs_altova_ENTITY.begin ;
	};


	public static class _altova_mi_xs_altova_ID {
		public static final int begin = _altova_mi_xs_altova_ENTITY.end ;
		public static final int end = _altova_mi_xs_altova_ID.begin ;
	};


	public static class _altova_mi_xs_altova_IDREF {
		public static final int begin = _altova_mi_xs_altova_ID.end ;
		public static final int end = _altova_mi_xs_altova_IDREF.begin ;
	};


	public static class _altova_mi_xs_altova_IDREFS {
		public static final int begin = _altova_mi_xs_altova_IDREF.end ;
		public static final int end = _altova_mi_xs_altova_IDREFS.begin ;
	};


	public static class _altova_mi_xs_altova_NCName {
		public static final int begin = _altova_mi_xs_altova_IDREFS.end ;
		public static final int end = _altova_mi_xs_altova_NCName.begin ;
	};


	public static class _altova_mi_xs_altova_NMTOKEN {
		public static final int begin = _altova_mi_xs_altova_NCName.end ;
		public static final int end = _altova_mi_xs_altova_NMTOKEN.begin ;
	};


	public static class _altova_mi_xs_altova_NMTOKENS {
		public static final int begin = _altova_mi_xs_altova_NMTOKEN.end ;
		public static final int end = _altova_mi_xs_altova_NMTOKENS.begin ;
	};


	public static class _altova_mi_xs_altova_NOTATION {
		public static final int begin = _altova_mi_xs_altova_NMTOKENS.end ;
		public static final int end = _altova_mi_xs_altova_NOTATION.begin ;
	};


	public static class _altova_mi_xs_altova_Name {
		public static final int begin = _altova_mi_xs_altova_NOTATION.end ;
		public static final int end = _altova_mi_xs_altova_Name.begin ;
	};


	public static class _altova_mi_xs_altova_QName {
		public static final int begin = _altova_mi_xs_altova_Name.end ;
		public static final int end = _altova_mi_xs_altova_QName.begin ;
	};


	public static class _altova_mi_xs_altova_anySimpleType {
		public static final int begin = _altova_mi_xs_altova_QName.end ;
		public static final int end = _altova_mi_xs_altova_anySimpleType.begin ;
	};


	public static class _altova_mi_xs_altova_anyType {
		public static final int begin = _altova_mi_xs_altova_anySimpleType.end ;
		public static final int _unnamed = _altova_mi_xs_altova_anyType.begin ;
		public static final int end = 24 ;
	};


	public static class _altova_mi_xs_altova_anyURI {
		public static final int begin = _altova_mi_xs_altova_anyType.end ;
		public static final int end = _altova_mi_xs_altova_anyURI.begin ;
	};


	public static class _altova_mi_xs_altova_base64Binary {
		public static final int begin = _altova_mi_xs_altova_anyURI.end ;
		public static final int end = _altova_mi_xs_altova_base64Binary.begin ;
	};


	public static class _altova_mi_xs_altova_boolean2 {
		public static final int begin = _altova_mi_xs_altova_base64Binary.end ;
		public static final int end = _altova_mi_xs_altova_boolean2.begin ;
	};


	public static class _altova_mi_xs_altova_byte2 {
		public static final int begin = _altova_mi_xs_altova_boolean2.end ;
		public static final int end = _altova_mi_xs_altova_byte2.begin ;
	};


	public static class _altova_mi_xs_altova_date {
		public static final int begin = _altova_mi_xs_altova_byte2.end ;
		public static final int end = _altova_mi_xs_altova_date.begin ;
	};


	public static class _altova_mi_xs_altova_dateTime {
		public static final int begin = _altova_mi_xs_altova_date.end ;
		public static final int end = _altova_mi_xs_altova_dateTime.begin ;
	};


	public static class _altova_mi_xs_altova_decimal {
		public static final int begin = _altova_mi_xs_altova_dateTime.end ;
		public static final int end = _altova_mi_xs_altova_decimal.begin ;
	};


	public static class _altova_mi_xs_altova_double2 {
		public static final int begin = _altova_mi_xs_altova_decimal.end ;
		public static final int end = _altova_mi_xs_altova_double2.begin ;
	};


	public static class _altova_mi_xs_altova_duration {
		public static final int begin = _altova_mi_xs_altova_double2.end ;
		public static final int end = _altova_mi_xs_altova_duration.begin ;
	};


	public static class _altova_mi_xs_altova_float2 {
		public static final int begin = _altova_mi_xs_altova_duration.end ;
		public static final int end = _altova_mi_xs_altova_float2.begin ;
	};


	public static class _altova_mi_xs_altova_gDay {
		public static final int begin = _altova_mi_xs_altova_float2.end ;
		public static final int end = _altova_mi_xs_altova_gDay.begin ;
	};


	public static class _altova_mi_xs_altova_gMonth {
		public static final int begin = _altova_mi_xs_altova_gDay.end ;
		public static final int end = _altova_mi_xs_altova_gMonth.begin ;
	};


	public static class _altova_mi_xs_altova_gMonthDay {
		public static final int begin = _altova_mi_xs_altova_gMonth.end ;
		public static final int end = _altova_mi_xs_altova_gMonthDay.begin ;
	};


	public static class _altova_mi_xs_altova_gYear {
		public static final int begin = _altova_mi_xs_altova_gMonthDay.end ;
		public static final int end = _altova_mi_xs_altova_gYear.begin ;
	};


	public static class _altova_mi_xs_altova_gYearMonth {
		public static final int begin = _altova_mi_xs_altova_gYear.end ;
		public static final int end = _altova_mi_xs_altova_gYearMonth.begin ;
	};


	public static class _altova_mi_xs_altova_hexBinary {
		public static final int begin = _altova_mi_xs_altova_gYearMonth.end ;
		public static final int end = _altova_mi_xs_altova_hexBinary.begin ;
	};


	public static class _altova_mi_xs_altova_int2 {
		public static final int begin = _altova_mi_xs_altova_hexBinary.end ;
		public static final int end = _altova_mi_xs_altova_int2.begin ;
	};


	public static class _altova_mi_xs_altova_integer {
		public static final int begin = _altova_mi_xs_altova_int2.end ;
		public static final int end = _altova_mi_xs_altova_integer.begin ;
	};


	public static class _altova_mi_xs_altova_language {
		public static final int begin = _altova_mi_xs_altova_integer.end ;
		public static final int end = _altova_mi_xs_altova_language.begin ;
	};


	public static class _altova_mi_xs_altova_long2 {
		public static final int begin = _altova_mi_xs_altova_language.end ;
		public static final int end = _altova_mi_xs_altova_long2.begin ;
	};


	public static class _altova_mi_xs_altova_negativeInteger {
		public static final int begin = _altova_mi_xs_altova_long2.end ;
		public static final int end = _altova_mi_xs_altova_negativeInteger.begin ;
	};


	public static class _altova_mi_xs_altova_nonNegativeInteger {
		public static final int begin = _altova_mi_xs_altova_negativeInteger.end ;
		public static final int end = _altova_mi_xs_altova_nonNegativeInteger.begin ;
	};


	public static class _altova_mi_xs_altova_nonPositiveInteger {
		public static final int begin = _altova_mi_xs_altova_nonNegativeInteger.end ;
		public static final int end = _altova_mi_xs_altova_nonPositiveInteger.begin ;
	};


	public static class _altova_mi_xs_altova_normalizedString {
		public static final int begin = _altova_mi_xs_altova_nonPositiveInteger.end ;
		public static final int end = _altova_mi_xs_altova_normalizedString.begin ;
	};


	public static class _altova_mi_xs_altova_positiveInteger {
		public static final int begin = _altova_mi_xs_altova_normalizedString.end ;
		public static final int end = _altova_mi_xs_altova_positiveInteger.begin ;
	};


	public static class _altova_mi_xs_altova_short2 {
		public static final int begin = _altova_mi_xs_altova_positiveInteger.end ;
		public static final int end = _altova_mi_xs_altova_short2.begin ;
	};


	public static class _altova_mi_xs_altova_string2 {
		public static final int begin = _altova_mi_xs_altova_short2.end ;
		public static final int end = _altova_mi_xs_altova_string2.begin ;
	};


	public static class _altova_mi_xs_altova_time {
		public static final int begin = _altova_mi_xs_altova_string2.end ;
		public static final int end = _altova_mi_xs_altova_time.begin ;
	};


	public static class _altova_mi_xs_altova_token {
		public static final int begin = _altova_mi_xs_altova_time.end ;
		public static final int end = _altova_mi_xs_altova_token.begin ;
	};


	public static class _altova_mi_xs_altova_unsignedByte {
		public static final int begin = _altova_mi_xs_altova_token.end ;
		public static final int end = _altova_mi_xs_altova_unsignedByte.begin ;
	};


	public static class _altova_mi_xs_altova_unsignedInt {
		public static final int begin = _altova_mi_xs_altova_unsignedByte.end ;
		public static final int end = _altova_mi_xs_altova_unsignedInt.begin ;
	};


	public static class _altova_mi_xs_altova_unsignedLong {
		public static final int begin = _altova_mi_xs_altova_unsignedInt.end ;
		public static final int end = _altova_mi_xs_altova_unsignedLong.begin ;
	};


	public static class _altova_mi_xs_altova_unsignedShort {
		public static final int begin = _altova_mi_xs_altova_unsignedLong.end ;
		public static final int end = _altova_mi_xs_altova_unsignedShort.begin ;
	};

	

	public static class InfoBinder implements InfoBinderInterface
	{
		public NamespaceInfo[] getNamespaces() {return namespaces;}
		public TypeInfo[] getTypes() {return types;}
		public MemberInfo[] getMembers() {return members;}
	}
	
	public static InfoBinderInterface binder = new InfoBinder();

	// Array of all namespaces with pointers to types:
	public static final NamespaceInfo namespaces[] = 
	{
		new NamespaceInfo(binder, "", "", _altova_tif, _altova_til),
		new NamespaceInfo(binder, "http://www.w3.org/2001/XMLSchema", "xs", _altova_tif_xs, _altova_til_xs),
	};

	
// Array of all types with pointers to members:
	public static final TypeInfo types[] = new TypeInfoCreator().createTypes(binder);

	private static class TypeInfoCreator
	{
		private void initTypes0(InfoBinderInterface binder, TypeInfo[] types) {
			types[0] = new TypeInfo( binder, _altova_ni, "com.jbpm3processdocgpd", 0, _altova_mi_altova_jbpm3processdocgpd2.begin, _altova_mi_altova_jbpm3processdocgpd2.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[1] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_bendpointType.begin, _altova_mi_altova_bendpointType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[2] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_short2, _altova_mi_altova_w2Type.begin, _altova_mi_altova_w2Type.end,  null, 				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.IntegerFormatter );
			types[3] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_short2, _altova_mi_altova_w1Type.begin, _altova_mi_altova_w1Type.end,  null, 				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.IntegerFormatter );
			types[4] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_short2, _altova_mi_altova_h2Type.begin, _altova_mi_altova_h2Type.end,  null, 				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.IntegerFormatter );
			types[5] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_short2, _altova_mi_altova_h1Type.begin, _altova_mi_altova_h1Type.end,  null, 				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.IntegerFormatter );
			types[6] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_edgeType.begin, _altova_mi_altova_edgeType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[7] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_labelType.begin, _altova_mi_altova_labelType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[8] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_nodeType.begin, _altova_mi_altova_nodeType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[9] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_short2, _altova_mi_altova_yType.begin, _altova_mi_altova_yType.end,  null, 				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.IntegerFormatter );
			types[10] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_short2, _altova_mi_altova_xType.begin, _altova_mi_altova_xType.end,  null, 				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.IntegerFormatter );
			types[11] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_short2, _altova_mi_altova_widthType.begin, _altova_mi_altova_widthType.end,  null, 				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.IntegerFormatter );
			types[12] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_byte2, _altova_mi_altova_heightType.begin, _altova_mi_altova_heightType.end,  null, 				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.IntegerFormatter );
			types[13] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_root_containerType.begin, _altova_mi_altova_root_containerType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[14] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_short2, _altova_mi_altova_widthType2.begin, _altova_mi_altova_widthType2.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "enumeration", "881", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.IntegerFormatter );
			types[15] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_string2, _altova_mi_altova_nameType.begin, _altova_mi_altova_nameType.end,  
				new FacetInfo[]
				{
					new FacetInfo (com.migration.xml.XsValidation.facetCheck_string_enumeration, "enumeration", "accountant_Fixed_Asset_Disposal", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[16] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_short2, _altova_mi_altova_heightType2.begin, _altova_mi_altova_heightType2.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "enumeration", "2922", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.IntegerFormatter );
			types[17] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_byte2, _altova_mi_altova_yType2.begin, _altova_mi_altova_yType2.end,  null, 				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.IntegerFormatter );
			types[18] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_byte2, _altova_mi_altova_xType2.begin, _altova_mi_altova_xType2.end,  null, 				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.IntegerFormatter );

			types[19] = new TypeInfo( binder, _altova_ni_xs, "ENTITIES", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_ENTITIES.begin, _altova_mi_xs_altova_ENTITIES.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
					new FacetInfo (null, "minLength", "1", 1 ), 
				},
				WhitespaceType.Whitespace_Collapse, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[20] = new TypeInfo( binder, _altova_ni_xs, "ENTITY", _altova_ti_xs_altova_NCName, _altova_mi_xs_altova_ENTITY.begin, _altova_mi_xs_altova_ENTITY.end,  null, 				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[21] = new TypeInfo( binder, _altova_ni_xs, "ID", _altova_ti_xs_altova_NCName, _altova_mi_xs_altova_ID.begin, _altova_mi_xs_altova_ID.end,  null, 				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[22] = new TypeInfo( binder, _altova_ni_xs, "IDREF", _altova_ti_xs_altova_NCName, _altova_mi_xs_altova_IDREF.begin, _altova_mi_xs_altova_IDREF.end,  null, 				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[23] = new TypeInfo( binder, _altova_ni_xs, "IDREFS", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_IDREFS.begin, _altova_mi_xs_altova_IDREFS.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
					new FacetInfo (null, "minLength", "1", 1 ), 
				},
				WhitespaceType.Whitespace_Collapse, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[24] = new TypeInfo( binder, _altova_ni_xs, "NCName", _altova_ti_xs_altova_Name, _altova_mi_xs_altova_NCName.begin, _altova_mi_xs_altova_NCName.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "pattern", "[\\i-[:]][\\c-[:]]*", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[25] = new TypeInfo( binder, _altova_ni_xs, "NMTOKEN", _altova_ti_xs_altova_token, _altova_mi_xs_altova_NMTOKEN.begin, _altova_mi_xs_altova_NMTOKEN.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "pattern", "\\c+", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[26] = new TypeInfo( binder, _altova_ni_xs, "NMTOKENS", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_NMTOKENS.begin, _altova_mi_xs_altova_NMTOKENS.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
					new FacetInfo (null, "minLength", "1", 1 ), 
					new FacetInfo (null, "pattern", "\\c+", 0 ), 
					new FacetInfo (null, "pattern", "\\c+", 0 ), 
				},
				WhitespaceType.Whitespace_Collapse, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[27] = new TypeInfo( binder, _altova_ni_xs, "NOTATION", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_NOTATION.begin, _altova_mi_xs_altova_NOTATION.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[28] = new TypeInfo( binder, _altova_ni_xs, "Name", _altova_ti_xs_altova_token, _altova_mi_xs_altova_Name.begin, _altova_mi_xs_altova_Name.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "pattern", "\\i\\c*", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[29] = new TypeInfo( binder, _altova_ni_xs, "QName", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_QName.begin, _altova_mi_xs_altova_QName.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[30] = new TypeInfo( binder, _altova_ni_xs, "anySimpleType", 0, _altova_mi_xs_altova_anySimpleType.begin, _altova_mi_xs_altova_anySimpleType.end,  null, 				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[31] = new TypeInfo( binder, _altova_ni_xs, "anyType", 0, _altova_mi_xs_altova_anyType.begin, _altova_mi_xs_altova_anyType.end,  null, 				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[32] = new TypeInfo( binder, _altova_ni_xs, "anyURI", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_anyURI.begin, _altova_mi_xs_altova_anyURI.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[33] = new TypeInfo( binder, _altova_ni_xs, "base64Binary", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_base64Binary.begin, _altova_mi_xs_altova_base64Binary.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[34] = new TypeInfo( binder, _altova_ni_xs, "boolean", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_boolean2.begin, _altova_mi_xs_altova_boolean2.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[35] = new TypeInfo( binder, _altova_ni_xs, "byte", _altova_ti_xs_altova_short2, _altova_mi_xs_altova_byte2.begin, _altova_mi_xs_altova_byte2.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "minInclusive", "-128", 0 ), 
					new FacetInfo (null, "maxInclusive", "127", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.IntegerFormatter );
			types[36] = new TypeInfo( binder, _altova_ni_xs, "date", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_date.begin, _altova_mi_xs_altova_date.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.migration.xml.Xs.DateFormatter );
			types[37] = new TypeInfo( binder, _altova_ni_xs, "dateTime", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_dateTime.begin, _altova_mi_xs_altova_dateTime.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.migration.xml.Xs.DateTimeFormatter );
			types[38] = new TypeInfo( binder, _altova_ni_xs, "decimal", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_decimal.begin, _altova_mi_xs_altova_decimal.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.migration.xml.Xs.DecimalFormatter );
			types[39] = new TypeInfo( binder, _altova_ni_xs, "double", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_double2.begin, _altova_mi_xs_altova_double2.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.migration.xml.Xs.DoubleFormatter );
			types[40] = new TypeInfo( binder, _altova_ni_xs, "duration", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_duration.begin, _altova_mi_xs_altova_duration.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.migration.xml.Xs.DurationFormatter );
			types[41] = new TypeInfo( binder, _altova_ni_xs, "float", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_float2.begin, _altova_mi_xs_altova_float2.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.migration.xml.Xs.DoubleFormatter );
			types[42] = new TypeInfo( binder, _altova_ni_xs, "gDay", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_gDay.begin, _altova_mi_xs_altova_gDay.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.migration.xml.Xs.GDayFormatter );
			types[43] = new TypeInfo( binder, _altova_ni_xs, "gMonth", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_gMonth.begin, _altova_mi_xs_altova_gMonth.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.migration.xml.Xs.GMonthFormatter );
			types[44] = new TypeInfo( binder, _altova_ni_xs, "gMonthDay", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_gMonthDay.begin, _altova_mi_xs_altova_gMonthDay.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.migration.xml.Xs.GMonthDayFormatter );
			types[45] = new TypeInfo( binder, _altova_ni_xs, "gYear", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_gYear.begin, _altova_mi_xs_altova_gYear.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.migration.xml.Xs.GYearFormatter );
			types[46] = new TypeInfo( binder, _altova_ni_xs, "gYearMonth", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_gYearMonth.begin, _altova_mi_xs_altova_gYearMonth.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.migration.xml.Xs.GYearMonthFormatter );
			types[47] = new TypeInfo( binder, _altova_ni_xs, "hexBinary", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_hexBinary.begin, _altova_mi_xs_altova_hexBinary.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.migration.xml.Xs.HexBinaryFormatter );
			types[48] = new TypeInfo( binder, _altova_ni_xs, "int", _altova_ti_xs_altova_long2, _altova_mi_xs_altova_int2.begin, _altova_mi_xs_altova_int2.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "minInclusive", "-2147483648", 0 ), 
					new FacetInfo (null, "maxInclusive", "2147483647", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.IntegerFormatter );
			types[49] = new TypeInfo( binder, _altova_ni_xs, "integer", _altova_ti_xs_altova_decimal, _altova_mi_xs_altova_integer.begin, _altova_mi_xs_altova_integer.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "fractionDigits", "0", 0 ), 
					new FacetInfo (null, "pattern", "[\\-+]?[0-9]+", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.IntegerFormatter );
			types[50] = new TypeInfo( binder, _altova_ni_xs, "language", _altova_ti_xs_altova_token, _altova_mi_xs_altova_language.begin, _altova_mi_xs_altova_language.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "pattern", "[a-zA-Z]{1,8}(-[a-zA-Z0-9]{1,8})*", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[51] = new TypeInfo( binder, _altova_ni_xs, "long", _altova_ti_xs_altova_integer, _altova_mi_xs_altova_long2.begin, _altova_mi_xs_altova_long2.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "minInclusive", "-9223372036854775808", 0 ), 
					new FacetInfo (null, "maxInclusive", "9223372036854775807", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.IntegerFormatter );
			types[52] = new TypeInfo( binder, _altova_ni_xs, "negativeInteger", _altova_ti_xs_altova_nonPositiveInteger, _altova_mi_xs_altova_negativeInteger.begin, _altova_mi_xs_altova_negativeInteger.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "maxInclusive", "-1", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.IntegerFormatter );
			types[53] = new TypeInfo( binder, _altova_ni_xs, "nonNegativeInteger", _altova_ti_xs_altova_integer, _altova_mi_xs_altova_nonNegativeInteger.begin, _altova_mi_xs_altova_nonNegativeInteger.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "minInclusive", "0", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.IntegerFormatter );
			types[54] = new TypeInfo( binder, _altova_ni_xs, "nonPositiveInteger", _altova_ti_xs_altova_integer, _altova_mi_xs_altova_nonPositiveInteger.begin, _altova_mi_xs_altova_nonPositiveInteger.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "maxInclusive", "0", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.IntegerFormatter );
			types[55] = new TypeInfo( binder, _altova_ni_xs, "normalizedString", _altova_ti_xs_altova_string2, _altova_mi_xs_altova_normalizedString.begin, _altova_mi_xs_altova_normalizedString.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "replace", 0 ),
				},
				WhitespaceType.Whitespace_Replace, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[56] = new TypeInfo( binder, _altova_ni_xs, "positiveInteger", _altova_ti_xs_altova_nonNegativeInteger, _altova_mi_xs_altova_positiveInteger.begin, _altova_mi_xs_altova_positiveInteger.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "minInclusive", "1", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.IntegerFormatter );
			types[57] = new TypeInfo( binder, _altova_ni_xs, "short", _altova_ti_xs_altova_int2, _altova_mi_xs_altova_short2.begin, _altova_mi_xs_altova_short2.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "minInclusive", "-32768", 0 ), 
					new FacetInfo (null, "maxInclusive", "32767", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.IntegerFormatter );
			types[58] = new TypeInfo( binder, _altova_ni_xs, "string", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_string2.begin, _altova_mi_xs_altova_string2.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "preserve", 0 ),
				},
				WhitespaceType.Whitespace_Preserve, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[59] = new TypeInfo( binder, _altova_ni_xs, "time", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_time.begin, _altova_mi_xs_altova_time.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.migration.xml.Xs.TimeFormatter );
			types[60] = new TypeInfo( binder, _altova_ni_xs, "token", _altova_ti_xs_altova_normalizedString, _altova_mi_xs_altova_token.begin, _altova_mi_xs_altova_token.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[61] = new TypeInfo( binder, _altova_ni_xs, "unsignedByte", _altova_ti_xs_altova_unsignedShort, _altova_mi_xs_altova_unsignedByte.begin, _altova_mi_xs_altova_unsignedByte.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "maxInclusive", "255", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.IntegerFormatter );
			types[62] = new TypeInfo( binder, _altova_ni_xs, "unsignedInt", _altova_ti_xs_altova_unsignedLong, _altova_mi_xs_altova_unsignedInt.begin, _altova_mi_xs_altova_unsignedInt.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "maxInclusive", "4294967295", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.IntegerFormatter );
			types[63] = new TypeInfo( binder, _altova_ni_xs, "unsignedLong", _altova_ti_xs_altova_nonNegativeInteger, _altova_mi_xs_altova_unsignedLong.begin, _altova_mi_xs_altova_unsignedLong.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "maxInclusive", "18446744073709551615", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.IntegerFormatter );
			types[64] = new TypeInfo( binder, _altova_ni_xs, "unsignedShort", _altova_ti_xs_altova_unsignedInt, _altova_mi_xs_altova_unsignedShort.begin, _altova_mi_xs_altova_unsignedShort.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "maxInclusive", "65535", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.IntegerFormatter );

		}

		public TypeInfo[] createTypes(InfoBinderInterface binder) {

			TypeInfo types[] = new TypeInfo[65];

			initTypes0(binder, types);
			
			return types;

		}
	}

	// Array of all members
	public static final MemberInfo members[] = new MemberInfoCreator().createMembers(binder);

	private static class MemberInfoCreator
	{
		private void initMembers0(InfoBinderInterface binder, MemberInfo[] members) {
			members[0] = new MemberInfo (binder, "", "bendpoint", _altova_ti_altova_jbpm3processdocgpd2, _altova_ti_altova_bendpointType, 0, 0, 1);
			members[1] = new MemberInfo (binder, "", "edge", _altova_ti_altova_jbpm3processdocgpd2, _altova_ti_altova_edgeType, 0, 0, 1);
			members[2] = new MemberInfo (binder, "", "label", _altova_ti_altova_jbpm3processdocgpd2, _altova_ti_altova_labelType, 0, 0, 1);
			members[3] = new MemberInfo (binder, "", "node", _altova_ti_altova_jbpm3processdocgpd2, _altova_ti_altova_nodeType, 0, 0, 1);
			members[4] = new MemberInfo (binder, "", "root-container", _altova_ti_altova_jbpm3processdocgpd2, _altova_ti_altova_root_containerType, 0, 0, 1);

			members[5] = new MemberInfo (binder, "", "w2", _altova_ti_altova_bendpointType, _altova_ti_altova_w2Type, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);
			members[6] = new MemberInfo (binder, "", "w1", _altova_ti_altova_bendpointType, _altova_ti_altova_w1Type, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);
			members[7] = new MemberInfo (binder, "", "h2", _altova_ti_altova_bendpointType, _altova_ti_altova_h2Type, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);
			members[8] = new MemberInfo (binder, "", "h1", _altova_ti_altova_bendpointType, _altova_ti_altova_h1Type, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);

			members[9] = new MemberInfo (binder, "", "label", _altova_ti_altova_edgeType, _altova_ti_altova_labelType, 0, 1, 1);
			members[10] = new MemberInfo (binder, "", "bendpoint", _altova_ti_altova_edgeType, _altova_ti_altova_bendpointType, 0, 0, -1);

			members[11] = new MemberInfo (binder, "", "y", _altova_ti_altova_labelType, _altova_ti_altova_yType2, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);
			members[12] = new MemberInfo (binder, "", "x", _altova_ti_altova_labelType, _altova_ti_altova_xType2, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);

			members[13] = new MemberInfo (binder, "", "y", _altova_ti_altova_nodeType, _altova_ti_altova_yType, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);
			members[14] = new MemberInfo (binder, "", "x", _altova_ti_altova_nodeType, _altova_ti_altova_xType, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);
			members[15] = new MemberInfo (binder, "", "width", _altova_ti_altova_nodeType, _altova_ti_altova_widthType, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);
			members[16] = new MemberInfo (binder, "", "name", _altova_ti_altova_nodeType, _altova_ti_xs_altova_string2, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);
			members[17] = new MemberInfo (binder, "", "height", _altova_ti_altova_nodeType, _altova_ti_altova_heightType, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);
			members[18] = new MemberInfo (binder, "", "edge", _altova_ti_altova_nodeType, _altova_ti_altova_edgeType, 0, 0, -1);

			members[19] = new MemberInfo (binder, "", "width", _altova_ti_altova_root_containerType, _altova_ti_altova_widthType2, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);
			members[20] = new MemberInfo (binder, "", "name", _altova_ti_altova_root_containerType, _altova_ti_altova_nameType, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);
			members[21] = new MemberInfo (binder, "", "height", _altova_ti_altova_root_containerType, _altova_ti_altova_heightType2, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);
			members[22] = new MemberInfo (binder, "", "node", _altova_ti_altova_root_containerType, _altova_ti_altova_nodeType, 0, 1, -1);

			members[23] = new MemberInfo (binder, "", "", _altova_ti_xs_altova_anyType, _altova_ti_xs_altova_anySimpleType, 0|MemberInfo.IS_ATTRIBUTE, 0, -1);

		}

		public MemberInfo[] createMembers(InfoBinderInterface binder) {

			MemberInfo members[] = new MemberInfo[24];

			initMembers0(binder, members);
			
			return members;

		}
	}
}
