////////////////////////////////////////////////////////////////////////
//
// jbpm5v2_typeinfo.java
//
// This file was generated by XMLSpy 2009sp1 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//
////////////////////////////////////////////////////////////////////////


package com.jbpm5v2;

import com.migration.typeinfo.*;



public class jbpm5v2_TypeInfo
{
	// namespaces indices
	public static final int _altova_ni_tns = 0;
	public static final int _altova_ni_bpmndi = 1;
	public static final int _altova_ni = 2;
	public static final int _altova_ni_dc = 3;
	public static final int _altova_ni_di = 4;
	public static final int _altova_ni_xs = 5;


	// typeinfo indices
	public static final int _altova_tif_tns = 0 ;
	public static final int _altova_til_tns = _altova_tif_tns ;

	public static final int _altova_tif_bpmndi = _altova_til_tns;
	public static final int _altova_til_bpmndi = _altova_tif_bpmndi ;

	public static final int _altova_tif = _altova_til_bpmndi;
	public static final int _altova_ti_altova_tFormalExpression = _altova_tif ;
	public static final int _altova_ti_altova_jbpm5v22 = 1 ;
	public static final int _altova_ti_altova_onEntry_scriptType = 2 ;
	public static final int _altova_ti_altova_scriptFormatType = 3 ;
	public static final int _altova_ti_altova_scriptType = 4 ;
	public static final int _altova_ti_altova_onExit_scriptType = 5 ;
	public static final int _altova_ti_altova_scriptFormatType2 = 6 ;
	public static final int _altova_ti_altova_BPMNDiagramType = 7 ;
	public static final int _altova_ti_altova_BPMNPlaneType = 8 ;
	public static final int _altova_ti_altova_BPMNEdgeType = 9 ;
	public static final int _altova_ti_altova_bpmnElementType = 10 ;
	public static final int _altova_ti_altova_waypointType = 11 ;
	public static final int _altova_ti_altova_BPMNShapeType = 12 ;
	public static final int _altova_ti_altova_bpmnElementType2 = 13 ;
	public static final int _altova_ti_altova_BoundsType = 14 ;
	public static final int _altova_ti_altova_assignmentType = 15 ;
	public static final int _altova_ti_altova_conditionExpressionType = 16 ;
	public static final int _altova_ti_altova_typeType = 17 ;
	public static final int _altova_ti_altova_dataInputType = 18 ;
	public static final int _altova_ti_altova_nameType = 19 ;
	public static final int _altova_ti_altova_idType = 20 ;
	public static final int _altova_ti_altova_dataInputAssociationType = 21 ;
	public static final int _altova_ti_altova_targetRefType = 22 ;
	public static final int _altova_ti_altova_sourceRefType = 23 ;
	public static final int _altova_ti_altova_dataInputRefsType = 24 ;
	public static final int _altova_ti_altova_dataInputRefsType2 = 25 ;
	public static final int _altova_ti_altova_dataOutputType = 26 ;
	public static final int _altova_ti_altova_nameType2 = 27 ;
	public static final int _altova_ti_altova_idType2 = 28 ;
	public static final int _altova_ti_altova_dataOutputAssociationType = 29 ;
	public static final int _altova_ti_altova_dataOutputRefsType = 30 ;
	public static final int _altova_ti_altova_dataOutputRefsType2 = 31 ;
	public static final int _altova_ti_altova_definitionsType = 32 ;
	public static final int _altova_ti_altova_typeLanguageType = 33 ;
	public static final int _altova_ti_altova_targetNamespaceType = 34 ;
	public static final int _altova_ti_altova_idType3 = 35 ;
	public static final int _altova_ti_altova_expressionLanguageType = 36 ;
	public static final int _altova_ti_altova_processType = 37 ;
	public static final int _altova_ti_altova_endEventType = 38 ;
	public static final int _altova_ti_altova_nameType3 = 39 ;
	public static final int _altova_ti_altova_idType4 = 40 ;
	public static final int _altova_ti_altova_exclusiveGatewayType = 41 ;
	public static final int _altova_ti_altova_nameType4 = 42 ;
	public static final int _altova_ti_altova_idType5 = 43 ;
	public static final int _altova_ti_altova_gatewayDirectionType = 44 ;
	public static final int _altova_ti_altova_extensionElementsType = 45 ;
	public static final int _altova_ti_altova_formalExpressionType = 46 ;
	public static final int _altova_ti_altova_formalExpressionType2 = 47 ;
	public static final int _altova_ti_altova_inputSetType = 48 ;
	public static final int _altova_ti_altova_ioSpecificationType = 49 ;
	public static final int _altova_ti_altova_outputSetType = 50 ;
	public static final int _altova_ti_altova_potentialOwnerType = 51 ;
	public static final int _altova_ti_altova_resourceAssignmentExpressionType = 52 ;
	public static final int _altova_ti_altova_sequenceFlowType = 53 ;
	public static final int _altova_ti_altova_targetRefType2 = 54 ;
	public static final int _altova_ti_altova_sourceRefType2 = 55 ;
	public static final int _altova_ti_altova_idType6 = 56 ;
	public static final int _altova_ti_altova_startEventType = 57 ;
	public static final int _altova_ti_altova_nameType5 = 58 ;
	public static final int _altova_ti_altova_idType7 = 59 ;
	public static final int _altova_ti_altova_userTaskType = 60 ;
	public static final int _altova_ti_altova_nameType6 = 61 ;
	public static final int _altova_ti_altova_idType8 = 62 ;
	public static final int _altova_ti_altova_yType = 63 ;
	public static final int _altova_ti_altova_xType = 64 ;
	public static final int _altova_ti_altova_yType2 = 65 ;
	public static final int _altova_ti_altova_xType2 = 66 ;
	public static final int _altova_ti_altova_widthType = 67 ;
	public static final int _altova_ti_altova_heightType = 68 ;
	public static final int _altova_ti_altova_processTypeType = 69 ;
	public static final int _altova_til = 70 ;

	public static final int _altova_tif_dc = _altova_til;
	public static final int _altova_til_dc = _altova_tif_dc ;

	public static final int _altova_tif_di = _altova_til_dc;
	public static final int _altova_til_di = _altova_tif_di ;

	public static final int _altova_tif_xs = _altova_til_di;
	public static final int _altova_ti_xs_altova_ENTITIES = _altova_tif_xs ;
	public static final int _altova_ti_xs_altova_ENTITY = 71 ;
	public static final int _altova_ti_xs_altova_ID = 72 ;
	public static final int _altova_ti_xs_altova_IDREF = 73 ;
	public static final int _altova_ti_xs_altova_IDREFS = 74 ;
	public static final int _altova_ti_xs_altova_NCName = 75 ;
	public static final int _altova_ti_xs_altova_NMTOKEN = 76 ;
	public static final int _altova_ti_xs_altova_NMTOKENS = 77 ;
	public static final int _altova_ti_xs_altova_NOTATION = 78 ;
	public static final int _altova_ti_xs_altova_Name = 79 ;
	public static final int _altova_ti_xs_altova_QName = 80 ;
	public static final int _altova_ti_xs_altova_anySimpleType = 81 ;
	public static final int _altova_ti_xs_altova_anyType = 82 ;
	public static final int _altova_ti_xs_altova_anyURI = 83 ;
	public static final int _altova_ti_xs_altova_base64Binary = 84 ;
	public static final int _altova_ti_xs_altova_boolean2 = 85 ;
	public static final int _altova_ti_xs_altova_byte2 = 86 ;
	public static final int _altova_ti_xs_altova_date = 87 ;
	public static final int _altova_ti_xs_altova_dateTime = 88 ;
	public static final int _altova_ti_xs_altova_decimal = 89 ;
	public static final int _altova_ti_xs_altova_double2 = 90 ;
	public static final int _altova_ti_xs_altova_duration = 91 ;
	public static final int _altova_ti_xs_altova_float2 = 92 ;
	public static final int _altova_ti_xs_altova_gDay = 93 ;
	public static final int _altova_ti_xs_altova_gMonth = 94 ;
	public static final int _altova_ti_xs_altova_gMonthDay = 95 ;
	public static final int _altova_ti_xs_altova_gYear = 96 ;
	public static final int _altova_ti_xs_altova_gYearMonth = 97 ;
	public static final int _altova_ti_xs_altova_hexBinary = 98 ;
	public static final int _altova_ti_xs_altova_int2 = 99 ;
	public static final int _altova_ti_xs_altova_integer = 100 ;
	public static final int _altova_ti_xs_altova_language = 101 ;
	public static final int _altova_ti_xs_altova_long2 = 102 ;
	public static final int _altova_ti_xs_altova_negativeInteger = 103 ;
	public static final int _altova_ti_xs_altova_nonNegativeInteger = 104 ;
	public static final int _altova_ti_xs_altova_nonPositiveInteger = 105 ;
	public static final int _altova_ti_xs_altova_normalizedString = 106 ;
	public static final int _altova_ti_xs_altova_positiveInteger = 107 ;
	public static final int _altova_ti_xs_altova_short2 = 108 ;
	public static final int _altova_ti_xs_altova_string2 = 109 ;
	public static final int _altova_ti_xs_altova_time = 110 ;
	public static final int _altova_ti_xs_altova_token = 111 ;
	public static final int _altova_ti_xs_altova_unsignedByte = 112 ;
	public static final int _altova_ti_xs_altova_unsignedInt = 113 ;
	public static final int _altova_ti_xs_altova_unsignedLong = 114 ;
	public static final int _altova_ti_xs_altova_unsignedShort = 115 ;
	public static final int _altova_ti_xs_altova_stringType = 116 ;
	public static final int _altova_til_xs = 117 ;



	// memberinfo indices

	public static class _altova_mi_altova_tFormalExpression {
		public static final int begin = 0 ;
		public static final int end = _altova_mi_altova_tFormalExpression.begin ;
	};


	public static class _altova_mi_altova_jbpm5v22 {
		public static final int begin = _altova_mi_altova_tFormalExpression.end ;
		public static final int _onEntry_script = _altova_mi_altova_jbpm5v22.begin ;
		public static final int _onExit_script = 1 ;
		public static final int _script = 2 ;
		public static final int _BPMNDiagram = 3 ;
		public static final int _BPMNEdge = 4 ;
		public static final int _BPMNPlane = 5 ;
		public static final int _BPMNShape = 6 ;
		public static final int _assignment = 7 ;
		public static final int _conditionExpression = 8 ;
		public static final int _dataInput = 9 ;
		public static final int _dataInputAssociation = 10 ;
		public static final int _dataInputRefs = 11 ;
		public static final int _dataOutput = 12 ;
		public static final int _dataOutputAssociation = 13 ;
		public static final int _dataOutputRefs = 14 ;
		public static final int _definitions = 15 ;
		public static final int _endEvent = 16 ;
		public static final int _exclusiveGateway = 17 ;
		public static final int _extensionElements = 18 ;
		public static final int _formalExpression = 19 ;
		public static final int _from = 20 ;
		public static final int _inputSet = 21 ;
		public static final int _ioSpecification = 22 ;
		public static final int _outputSet = 23 ;
		public static final int _potentialOwner = 24 ;
		public static final int _process = 25 ;
		public static final int _resourceAssignmentExpression = 26 ;
		public static final int _sequenceFlow = 27 ;
		public static final int _sourceRef = 28 ;
		public static final int _startEvent = 29 ;
		public static final int _targetRef = 30 ;
		public static final int _to = 31 ;
		public static final int _userTask = 32 ;
		public static final int _Bounds = 33 ;
		public static final int _waypoint = 34 ;
		public static final int end = 35 ;
	};


	public static class _altova_mi_altova_onEntry_scriptType {
		public static final int begin = _altova_mi_altova_jbpm5v22.end ;
		public static final int _scriptFormat = _altova_mi_altova_onEntry_scriptType.begin ;
		public static final int _script = 36 ;
		public static final int end = 37 ;
	};


	public static class _altova_mi_altova_scriptFormatType {
		public static final int begin = _altova_mi_altova_onEntry_scriptType.end ;
		public static final int end = _altova_mi_altova_scriptFormatType.begin ;
	};


	public static class _altova_mi_altova_scriptType {
		public static final int begin = _altova_mi_altova_scriptFormatType.end ;
		public static final int _unnamed = _altova_mi_altova_scriptType.begin ;
		public static final int end = 38 ;
	};


	public static class _altova_mi_altova_onExit_scriptType {
		public static final int begin = _altova_mi_altova_scriptType.end ;
		public static final int _scriptFormat = _altova_mi_altova_onExit_scriptType.begin ;
		public static final int _script = 39 ;
		public static final int end = 40 ;
	};


	public static class _altova_mi_altova_scriptFormatType2 {
		public static final int begin = _altova_mi_altova_onExit_scriptType.end ;
		public static final int end = _altova_mi_altova_scriptFormatType2.begin ;
	};


	public static class _altova_mi_altova_BPMNDiagramType {
		public static final int begin = _altova_mi_altova_scriptFormatType2.end ;
		public static final int _BPMNPlane = _altova_mi_altova_BPMNDiagramType.begin ;
		public static final int end = 41 ;
	};


	public static class _altova_mi_altova_BPMNPlaneType {
		public static final int begin = _altova_mi_altova_BPMNDiagramType.end ;
		public static final int _bpmnElement = _altova_mi_altova_BPMNPlaneType.begin ;
		public static final int _BPMNShape = 42 ;
		public static final int _BPMNEdge = 43 ;
		public static final int end = 44 ;
	};


	public static class _altova_mi_altova_BPMNEdgeType {
		public static final int begin = _altova_mi_altova_BPMNPlaneType.end ;
		public static final int _bpmnElement = _altova_mi_altova_BPMNEdgeType.begin ;
		public static final int _waypoint = 45 ;
		public static final int end = 46 ;
	};


	public static class _altova_mi_altova_bpmnElementType {
		public static final int begin = _altova_mi_altova_BPMNEdgeType.end ;
		public static final int end = _altova_mi_altova_bpmnElementType.begin ;
	};


	public static class _altova_mi_altova_waypointType {
		public static final int begin = _altova_mi_altova_bpmnElementType.end ;
		public static final int _y = _altova_mi_altova_waypointType.begin ;
		public static final int _x = 47 ;
		public static final int end = 48 ;
	};


	public static class _altova_mi_altova_BPMNShapeType {
		public static final int begin = _altova_mi_altova_waypointType.end ;
		public static final int _bpmnElement = _altova_mi_altova_BPMNShapeType.begin ;
		public static final int _Bounds = 49 ;
		public static final int end = 50 ;
	};


	public static class _altova_mi_altova_bpmnElementType2 {
		public static final int begin = _altova_mi_altova_BPMNShapeType.end ;
		public static final int end = _altova_mi_altova_bpmnElementType2.begin ;
	};


	public static class _altova_mi_altova_BoundsType {
		public static final int begin = _altova_mi_altova_bpmnElementType2.end ;
		public static final int _y = _altova_mi_altova_BoundsType.begin ;
		public static final int _x = 51 ;
		public static final int _width = 52 ;
		public static final int _height = 53 ;
		public static final int end = 54 ;
	};


	public static class _altova_mi_altova_assignmentType {
		public static final int begin = _altova_mi_altova_BoundsType.end ;
		public static final int _from = _altova_mi_altova_assignmentType.begin ;
		public static final int _to = 55 ;
		public static final int end = 56 ;
	};


	public static class _altova_mi_altova_conditionExpressionType {
		public static final int begin = _altova_mi_altova_assignmentType.end ;
		public static final int _type = _altova_mi_altova_conditionExpressionType.begin ;
		public static final int end = 57 ;
	};


	public static class _altova_mi_altova_typeType {
		public static final int begin = _altova_mi_altova_conditionExpressionType.end ;
		public static final int end = _altova_mi_altova_typeType.begin ;
	};


	public static class _altova_mi_altova_dataInputType {
		public static final int begin = _altova_mi_altova_typeType.end ;
		public static final int _name = _altova_mi_altova_dataInputType.begin ;
		public static final int _id = 58 ;
		public static final int end = 59 ;
	};


	public static class _altova_mi_altova_nameType {
		public static final int begin = _altova_mi_altova_dataInputType.end ;
		public static final int end = _altova_mi_altova_nameType.begin ;
	};


	public static class _altova_mi_altova_idType {
		public static final int begin = _altova_mi_altova_nameType.end ;
		public static final int end = _altova_mi_altova_idType.begin ;
	};


	public static class _altova_mi_altova_dataInputAssociationType {
		public static final int begin = _altova_mi_altova_idType.end ;
		public static final int _targetRef = _altova_mi_altova_dataInputAssociationType.begin ;
		public static final int _assignment = 60 ;
		public static final int _sourceRef = 61 ;
		public static final int end = 62 ;
	};


	public static class _altova_mi_altova_targetRefType {
		public static final int begin = _altova_mi_altova_dataInputAssociationType.end ;
		public static final int _unnamed = _altova_mi_altova_targetRefType.begin ;
		public static final int end = 63 ;
	};


	public static class _altova_mi_altova_sourceRefType {
		public static final int begin = _altova_mi_altova_targetRefType.end ;
		public static final int _unnamed = _altova_mi_altova_sourceRefType.begin ;
		public static final int end = 64 ;
	};


	public static class _altova_mi_altova_dataInputRefsType {
		public static final int begin = _altova_mi_altova_sourceRefType.end ;
		public static final int _unnamed = _altova_mi_altova_dataInputRefsType.begin ;
		public static final int end = 65 ;
	};


	public static class _altova_mi_altova_dataInputRefsType2 {
		public static final int begin = _altova_mi_altova_dataInputRefsType.end ;
		public static final int end = _altova_mi_altova_dataInputRefsType2.begin ;
	};


	public static class _altova_mi_altova_dataOutputType {
		public static final int begin = _altova_mi_altova_dataInputRefsType2.end ;
		public static final int _name = _altova_mi_altova_dataOutputType.begin ;
		public static final int _id = 66 ;
		public static final int end = 67 ;
	};


	public static class _altova_mi_altova_nameType2 {
		public static final int begin = _altova_mi_altova_dataOutputType.end ;
		public static final int end = _altova_mi_altova_nameType2.begin ;
	};


	public static class _altova_mi_altova_idType2 {
		public static final int begin = _altova_mi_altova_nameType2.end ;
		public static final int end = _altova_mi_altova_idType2.begin ;
	};


	public static class _altova_mi_altova_dataOutputAssociationType {
		public static final int begin = _altova_mi_altova_idType2.end ;
		public static final int _sourceRef = _altova_mi_altova_dataOutputAssociationType.begin ;
		public static final int _targetRef = 68 ;
		public static final int end = 69 ;
	};


	public static class _altova_mi_altova_dataOutputRefsType {
		public static final int begin = _altova_mi_altova_dataOutputAssociationType.end ;
		public static final int _unnamed = _altova_mi_altova_dataOutputRefsType.begin ;
		public static final int end = 70 ;
	};


	public static class _altova_mi_altova_dataOutputRefsType2 {
		public static final int begin = _altova_mi_altova_dataOutputRefsType.end ;
		public static final int end = _altova_mi_altova_dataOutputRefsType2.begin ;
	};


	public static class _altova_mi_altova_definitionsType {
		public static final int begin = _altova_mi_altova_dataOutputRefsType2.end ;
		public static final int _typeLanguage = _altova_mi_altova_definitionsType.begin ;
		public static final int _targetNamespace = 71 ;
		public static final int _id = 72 ;
		public static final int _expressionLanguage = 73 ;
		public static final int _process = 74 ;
		public static final int _BPMNDiagram = 75 ;
		public static final int end = 76 ;
	};


	public static class _altova_mi_altova_typeLanguageType {
		public static final int begin = _altova_mi_altova_definitionsType.end ;
		public static final int end = _altova_mi_altova_typeLanguageType.begin ;
	};


	public static class _altova_mi_altova_targetNamespaceType {
		public static final int begin = _altova_mi_altova_typeLanguageType.end ;
		public static final int end = _altova_mi_altova_targetNamespaceType.begin ;
	};


	public static class _altova_mi_altova_idType3 {
		public static final int begin = _altova_mi_altova_targetNamespaceType.end ;
		public static final int end = _altova_mi_altova_idType3.begin ;
	};


	public static class _altova_mi_altova_expressionLanguageType {
		public static final int begin = _altova_mi_altova_idType3.end ;
		public static final int end = _altova_mi_altova_expressionLanguageType.begin ;
	};


	public static class _altova_mi_altova_processType {
		public static final int begin = _altova_mi_altova_expressionLanguageType.end ;
		public static final int _packageName = _altova_mi_altova_processType.begin ;
		public static final int _processType2 = 77 ;
		public static final int _name = 78 ;
		public static final int _isExecutable = 79 ;
		public static final int _id = 80 ;
		public static final int _startEvent = 81 ;
		public static final int _userTask = 82 ;
		public static final int _exclusiveGateway = 83 ;
		public static final int _endEvent = 84 ;
		public static final int _sequenceFlow = 85 ;
		public static final int end = 86 ;
	};


	public static class _altova_mi_altova_endEventType {
		public static final int begin = _altova_mi_altova_processType.end ;
		public static final int _name = _altova_mi_altova_endEventType.begin ;
		public static final int _id = 87 ;
		public static final int end = 88 ;
	};


	public static class _altova_mi_altova_nameType3 {
		public static final int begin = _altova_mi_altova_endEventType.end ;
		public static final int end = _altova_mi_altova_nameType3.begin ;
	};


	public static class _altova_mi_altova_idType4 {
		public static final int begin = _altova_mi_altova_nameType3.end ;
		public static final int end = _altova_mi_altova_idType4.begin ;
	};


	public static class _altova_mi_altova_exclusiveGatewayType {
		public static final int begin = _altova_mi_altova_idType4.end ;
		public static final int _name = _altova_mi_altova_exclusiveGatewayType.begin ;
		public static final int _id = 89 ;
		public static final int _gatewayDirection = 90 ;
		public static final int end = 91 ;
	};


	public static class _altova_mi_altova_nameType4 {
		public static final int begin = _altova_mi_altova_exclusiveGatewayType.end ;
		public static final int end = _altova_mi_altova_nameType4.begin ;
	};


	public static class _altova_mi_altova_idType5 {
		public static final int begin = _altova_mi_altova_nameType4.end ;
		public static final int end = _altova_mi_altova_idType5.begin ;
	};


	public static class _altova_mi_altova_gatewayDirectionType {
		public static final int begin = _altova_mi_altova_idType5.end ;
		public static final int end = _altova_mi_altova_gatewayDirectionType.begin ;
	};


	public static class _altova_mi_altova_extensionElementsType {
		public static final int begin = _altova_mi_altova_gatewayDirectionType.end ;
		public static final int _onEntry_script = _altova_mi_altova_extensionElementsType.begin ;
		public static final int _onExit_script = 92 ;
		public static final int end = 93 ;
	};


	public static class _altova_mi_altova_formalExpressionType {
		public static final int begin = _altova_mi_altova_extensionElementsType.end ;
		public static final int _unnamed = _altova_mi_altova_formalExpressionType.begin ;
		public static final int end = 94 ;
	};


	public static class _altova_mi_altova_formalExpressionType2 {
		public static final int begin = _altova_mi_altova_formalExpressionType.end ;
		public static final int end = _altova_mi_altova_formalExpressionType2.begin ;
	};


	public static class _altova_mi_altova_inputSetType {
		public static final int begin = _altova_mi_altova_formalExpressionType2.end ;
		public static final int _unnamed = _altova_mi_altova_inputSetType.begin ;
		public static final int _dataInputRefs = 95 ;
		public static final int end = 96 ;
	};


	public static class _altova_mi_altova_ioSpecificationType {
		public static final int begin = _altova_mi_altova_inputSetType.end ;
		public static final int _inputSet = _altova_mi_altova_ioSpecificationType.begin ;
		public static final int _outputSet = 97 ;
		public static final int _dataInput = 98 ;
		public static final int _dataOutput = 99 ;
		public static final int end = 100 ;
	};


	public static class _altova_mi_altova_outputSetType {
		public static final int begin = _altova_mi_altova_ioSpecificationType.end ;
		public static final int _unnamed = _altova_mi_altova_outputSetType.begin ;
		public static final int _dataOutputRefs = 101 ;
		public static final int end = 102 ;
	};


	public static class _altova_mi_altova_potentialOwnerType {
		public static final int begin = _altova_mi_altova_outputSetType.end ;
		public static final int _resourceAssignmentExpression = _altova_mi_altova_potentialOwnerType.begin ;
		public static final int end = 103 ;
	};


	public static class _altova_mi_altova_resourceAssignmentExpressionType {
		public static final int begin = _altova_mi_altova_potentialOwnerType.end ;
		public static final int _formalExpression = _altova_mi_altova_resourceAssignmentExpressionType.begin ;
		public static final int end = 104 ;
	};


	public static class _altova_mi_altova_sequenceFlowType {
		public static final int begin = _altova_mi_altova_resourceAssignmentExpressionType.end ;
		public static final int _targetRef = _altova_mi_altova_sequenceFlowType.begin ;
		public static final int _sourceRef = 105 ;
		public static final int _id = 106 ;
		public static final int _conditionExpression = 107 ;
		public static final int end = 108 ;
	};


	public static class _altova_mi_altova_targetRefType2 {
		public static final int begin = _altova_mi_altova_sequenceFlowType.end ;
		public static final int end = _altova_mi_altova_targetRefType2.begin ;
	};


	public static class _altova_mi_altova_sourceRefType2 {
		public static final int begin = _altova_mi_altova_targetRefType2.end ;
		public static final int end = _altova_mi_altova_sourceRefType2.begin ;
	};


	public static class _altova_mi_altova_idType6 {
		public static final int begin = _altova_mi_altova_sourceRefType2.end ;
		public static final int end = _altova_mi_altova_idType6.begin ;
	};


	public static class _altova_mi_altova_startEventType {
		public static final int begin = _altova_mi_altova_idType6.end ;
		public static final int _name = _altova_mi_altova_startEventType.begin ;
		public static final int _id = 109 ;
		public static final int end = 110 ;
	};


	public static class _altova_mi_altova_nameType5 {
		public static final int begin = _altova_mi_altova_startEventType.end ;
		public static final int end = _altova_mi_altova_nameType5.begin ;
	};


	public static class _altova_mi_altova_idType7 {
		public static final int begin = _altova_mi_altova_nameType5.end ;
		public static final int end = _altova_mi_altova_idType7.begin ;
	};


	public static class _altova_mi_altova_userTaskType {
		public static final int begin = _altova_mi_altova_idType7.end ;
		public static final int _name = _altova_mi_altova_userTaskType.begin ;
		public static final int _id = 111 ;
		public static final int _ioSpecification = 112 ;
		public static final int _dataInputAssociation = 113 ;
		public static final int _extensionElements = 114 ;
		public static final int _dataOutputAssociation = 115 ;
		public static final int _potentialOwner = 116 ;
		public static final int end = 117 ;
	};


	public static class _altova_mi_altova_nameType6 {
		public static final int begin = _altova_mi_altova_userTaskType.end ;
		public static final int end = _altova_mi_altova_nameType6.begin ;
	};


	public static class _altova_mi_altova_idType8 {
		public static final int begin = _altova_mi_altova_nameType6.end ;
		public static final int end = _altova_mi_altova_idType8.begin ;
	};


	public static class _altova_mi_altova_yType {
		public static final int begin = _altova_mi_altova_idType8.end ;
		public static final int end = _altova_mi_altova_yType.begin ;
	};


	public static class _altova_mi_altova_xType {
		public static final int begin = _altova_mi_altova_yType.end ;
		public static final int end = _altova_mi_altova_xType.begin ;
	};


	public static class _altova_mi_altova_yType2 {
		public static final int begin = _altova_mi_altova_xType.end ;
		public static final int end = _altova_mi_altova_yType2.begin ;
	};


	public static class _altova_mi_altova_xType2 {
		public static final int begin = _altova_mi_altova_yType2.end ;
		public static final int end = _altova_mi_altova_xType2.begin ;
	};


	public static class _altova_mi_altova_widthType {
		public static final int begin = _altova_mi_altova_xType2.end ;
		public static final int end = _altova_mi_altova_widthType.begin ;
	};


	public static class _altova_mi_altova_heightType {
		public static final int begin = _altova_mi_altova_widthType.end ;
		public static final int end = _altova_mi_altova_heightType.begin ;
	};


	public static class _altova_mi_altova_processTypeType {
		public static final int begin = _altova_mi_altova_heightType.end ;
		public static final int end = _altova_mi_altova_processTypeType.begin ;
	};


	public static class _altova_mi_xs_altova_ENTITIES {
		public static final int begin = _altova_mi_altova_processTypeType.end ;
		public static final int end = _altova_mi_xs_altova_ENTITIES.begin ;
	};


	public static class _altova_mi_xs_altova_ENTITY {
		public static final int begin = _altova_mi_xs_altova_ENTITIES.end ;
		public static final int end = _altova_mi_xs_altova_ENTITY.begin ;
	};


	public static class _altova_mi_xs_altova_ID {
		public static final int begin = _altova_mi_xs_altova_ENTITY.end ;
		public static final int end = _altova_mi_xs_altova_ID.begin ;
	};


	public static class _altova_mi_xs_altova_IDREF {
		public static final int begin = _altova_mi_xs_altova_ID.end ;
		public static final int end = _altova_mi_xs_altova_IDREF.begin ;
	};


	public static class _altova_mi_xs_altova_IDREFS {
		public static final int begin = _altova_mi_xs_altova_IDREF.end ;
		public static final int end = _altova_mi_xs_altova_IDREFS.begin ;
	};


	public static class _altova_mi_xs_altova_NCName {
		public static final int begin = _altova_mi_xs_altova_IDREFS.end ;
		public static final int end = _altova_mi_xs_altova_NCName.begin ;
	};


	public static class _altova_mi_xs_altova_NMTOKEN {
		public static final int begin = _altova_mi_xs_altova_NCName.end ;
		public static final int end = _altova_mi_xs_altova_NMTOKEN.begin ;
	};


	public static class _altova_mi_xs_altova_NMTOKENS {
		public static final int begin = _altova_mi_xs_altova_NMTOKEN.end ;
		public static final int end = _altova_mi_xs_altova_NMTOKENS.begin ;
	};


	public static class _altova_mi_xs_altova_NOTATION {
		public static final int begin = _altova_mi_xs_altova_NMTOKENS.end ;
		public static final int end = _altova_mi_xs_altova_NOTATION.begin ;
	};


	public static class _altova_mi_xs_altova_Name {
		public static final int begin = _altova_mi_xs_altova_NOTATION.end ;
		public static final int end = _altova_mi_xs_altova_Name.begin ;
	};


	public static class _altova_mi_xs_altova_QName {
		public static final int begin = _altova_mi_xs_altova_Name.end ;
		public static final int end = _altova_mi_xs_altova_QName.begin ;
	};


	public static class _altova_mi_xs_altova_anySimpleType {
		public static final int begin = _altova_mi_xs_altova_QName.end ;
		public static final int end = _altova_mi_xs_altova_anySimpleType.begin ;
	};


	public static class _altova_mi_xs_altova_anyType {
		public static final int begin = _altova_mi_xs_altova_anySimpleType.end ;
		public static final int _unnamed = _altova_mi_xs_altova_anyType.begin ;
		public static final int end = 118 ;
	};


	public static class _altova_mi_xs_altova_anyURI {
		public static final int begin = _altova_mi_xs_altova_anyType.end ;
		public static final int end = _altova_mi_xs_altova_anyURI.begin ;
	};


	public static class _altova_mi_xs_altova_base64Binary {
		public static final int begin = _altova_mi_xs_altova_anyURI.end ;
		public static final int end = _altova_mi_xs_altova_base64Binary.begin ;
	};


	public static class _altova_mi_xs_altova_boolean2 {
		public static final int begin = _altova_mi_xs_altova_base64Binary.end ;
		public static final int end = _altova_mi_xs_altova_boolean2.begin ;
	};


	public static class _altova_mi_xs_altova_byte2 {
		public static final int begin = _altova_mi_xs_altova_boolean2.end ;
		public static final int end = _altova_mi_xs_altova_byte2.begin ;
	};


	public static class _altova_mi_xs_altova_date {
		public static final int begin = _altova_mi_xs_altova_byte2.end ;
		public static final int end = _altova_mi_xs_altova_date.begin ;
	};


	public static class _altova_mi_xs_altova_dateTime {
		public static final int begin = _altova_mi_xs_altova_date.end ;
		public static final int end = _altova_mi_xs_altova_dateTime.begin ;
	};


	public static class _altova_mi_xs_altova_decimal {
		public static final int begin = _altova_mi_xs_altova_dateTime.end ;
		public static final int end = _altova_mi_xs_altova_decimal.begin ;
	};


	public static class _altova_mi_xs_altova_double2 {
		public static final int begin = _altova_mi_xs_altova_decimal.end ;
		public static final int end = _altova_mi_xs_altova_double2.begin ;
	};


	public static class _altova_mi_xs_altova_duration {
		public static final int begin = _altova_mi_xs_altova_double2.end ;
		public static final int end = _altova_mi_xs_altova_duration.begin ;
	};


	public static class _altova_mi_xs_altova_float2 {
		public static final int begin = _altova_mi_xs_altova_duration.end ;
		public static final int end = _altova_mi_xs_altova_float2.begin ;
	};


	public static class _altova_mi_xs_altova_gDay {
		public static final int begin = _altova_mi_xs_altova_float2.end ;
		public static final int end = _altova_mi_xs_altova_gDay.begin ;
	};


	public static class _altova_mi_xs_altova_gMonth {
		public static final int begin = _altova_mi_xs_altova_gDay.end ;
		public static final int end = _altova_mi_xs_altova_gMonth.begin ;
	};


	public static class _altova_mi_xs_altova_gMonthDay {
		public static final int begin = _altova_mi_xs_altova_gMonth.end ;
		public static final int end = _altova_mi_xs_altova_gMonthDay.begin ;
	};


	public static class _altova_mi_xs_altova_gYear {
		public static final int begin = _altova_mi_xs_altova_gMonthDay.end ;
		public static final int end = _altova_mi_xs_altova_gYear.begin ;
	};


	public static class _altova_mi_xs_altova_gYearMonth {
		public static final int begin = _altova_mi_xs_altova_gYear.end ;
		public static final int end = _altova_mi_xs_altova_gYearMonth.begin ;
	};


	public static class _altova_mi_xs_altova_hexBinary {
		public static final int begin = _altova_mi_xs_altova_gYearMonth.end ;
		public static final int end = _altova_mi_xs_altova_hexBinary.begin ;
	};


	public static class _altova_mi_xs_altova_int2 {
		public static final int begin = _altova_mi_xs_altova_hexBinary.end ;
		public static final int end = _altova_mi_xs_altova_int2.begin ;
	};


	public static class _altova_mi_xs_altova_integer {
		public static final int begin = _altova_mi_xs_altova_int2.end ;
		public static final int end = _altova_mi_xs_altova_integer.begin ;
	};


	public static class _altova_mi_xs_altova_language {
		public static final int begin = _altova_mi_xs_altova_integer.end ;
		public static final int end = _altova_mi_xs_altova_language.begin ;
	};


	public static class _altova_mi_xs_altova_long2 {
		public static final int begin = _altova_mi_xs_altova_language.end ;
		public static final int end = _altova_mi_xs_altova_long2.begin ;
	};


	public static class _altova_mi_xs_altova_negativeInteger {
		public static final int begin = _altova_mi_xs_altova_long2.end ;
		public static final int end = _altova_mi_xs_altova_negativeInteger.begin ;
	};


	public static class _altova_mi_xs_altova_nonNegativeInteger {
		public static final int begin = _altova_mi_xs_altova_negativeInteger.end ;
		public static final int end = _altova_mi_xs_altova_nonNegativeInteger.begin ;
	};


	public static class _altova_mi_xs_altova_nonPositiveInteger {
		public static final int begin = _altova_mi_xs_altova_nonNegativeInteger.end ;
		public static final int end = _altova_mi_xs_altova_nonPositiveInteger.begin ;
	};


	public static class _altova_mi_xs_altova_normalizedString {
		public static final int begin = _altova_mi_xs_altova_nonPositiveInteger.end ;
		public static final int end = _altova_mi_xs_altova_normalizedString.begin ;
	};


	public static class _altova_mi_xs_altova_positiveInteger {
		public static final int begin = _altova_mi_xs_altova_normalizedString.end ;
		public static final int end = _altova_mi_xs_altova_positiveInteger.begin ;
	};


	public static class _altova_mi_xs_altova_short2 {
		public static final int begin = _altova_mi_xs_altova_positiveInteger.end ;
		public static final int end = _altova_mi_xs_altova_short2.begin ;
	};


	public static class _altova_mi_xs_altova_string2 {
		public static final int begin = _altova_mi_xs_altova_short2.end ;
		public static final int end = _altova_mi_xs_altova_string2.begin ;
	};


	public static class _altova_mi_xs_altova_time {
		public static final int begin = _altova_mi_xs_altova_string2.end ;
		public static final int end = _altova_mi_xs_altova_time.begin ;
	};


	public static class _altova_mi_xs_altova_token {
		public static final int begin = _altova_mi_xs_altova_time.end ;
		public static final int end = _altova_mi_xs_altova_token.begin ;
	};


	public static class _altova_mi_xs_altova_unsignedByte {
		public static final int begin = _altova_mi_xs_altova_token.end ;
		public static final int end = _altova_mi_xs_altova_unsignedByte.begin ;
	};


	public static class _altova_mi_xs_altova_unsignedInt {
		public static final int begin = _altova_mi_xs_altova_unsignedByte.end ;
		public static final int end = _altova_mi_xs_altova_unsignedInt.begin ;
	};


	public static class _altova_mi_xs_altova_unsignedLong {
		public static final int begin = _altova_mi_xs_altova_unsignedInt.end ;
		public static final int end = _altova_mi_xs_altova_unsignedLong.begin ;
	};


	public static class _altova_mi_xs_altova_unsignedShort {
		public static final int begin = _altova_mi_xs_altova_unsignedLong.end ;
		public static final int end = _altova_mi_xs_altova_unsignedShort.begin ;
	};


	public static class _altova_mi_xs_altova_stringType {
		public static final int begin = _altova_mi_xs_altova_unsignedShort.end ;
		public static final int _unnamed = _altova_mi_xs_altova_stringType.begin ;
		public static final int end = 119 ;
	};

	

	public static class InfoBinder implements InfoBinderInterface
	{
		public NamespaceInfo[] getNamespaces() {return namespaces;}
		public TypeInfo[] getTypes() {return types;}
		public MemberInfo[] getMembers() {return members;}
	}
	
	public static InfoBinderInterface binder = new InfoBinder();

	// Array of all namespaces with pointers to types:
	public static final NamespaceInfo namespaces[] = 
	{
		new NamespaceInfo(binder, "http://www.jboss.org/drools", "tns", _altova_tif_tns, _altova_til_tns),
		new NamespaceInfo(binder, "http://www.omg.org/spec/BPMN/20100524/DI", "bpmndi", _altova_tif_bpmndi, _altova_til_bpmndi),
		new NamespaceInfo(binder, "http://www.omg.org/spec/BPMN/20100524/MODEL", "", _altova_tif, _altova_til),
		new NamespaceInfo(binder, "http://www.omg.org/spec/DD/20100524/DC", "dc", _altova_tif_dc, _altova_til_dc),
		new NamespaceInfo(binder, "http://www.omg.org/spec/DD/20100524/DI", "di", _altova_tif_di, _altova_til_di),
		new NamespaceInfo(binder, "http://www.w3.org/2001/XMLSchema", "xs", _altova_tif_xs, _altova_til_xs),
	};

	
// Array of all types with pointers to members:
	public static final TypeInfo types[] = new TypeInfoCreator().createTypes(binder);

	private static class TypeInfoCreator
	{
		private void initTypes0(InfoBinderInterface binder, TypeInfo[] types) {


			types[0] = new TypeInfo( binder, _altova_ni, "tFormalExpression", _altova_ti_xs_altova_string2, _altova_mi_altova_tFormalExpression.begin, _altova_mi_altova_tFormalExpression.end,  null, 				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[1] = new TypeInfo( binder, _altova_ni, "jbpm5v2", 0, _altova_mi_altova_jbpm5v22.begin, _altova_mi_altova_jbpm5v22.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[2] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_onEntry_scriptType.begin, _altova_mi_altova_onEntry_scriptType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[3] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyURI, _altova_mi_altova_scriptFormatType.begin, _altova_mi_altova_scriptFormatType.end,  null, 				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[4] = new TypeInfo( binder, _altova_ni, "", 0, _altova_mi_altova_scriptType.begin, _altova_mi_altova_scriptType.end,  null, 				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[5] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_onExit_scriptType.begin, _altova_mi_altova_onExit_scriptType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[6] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyURI, _altova_mi_altova_scriptFormatType2.begin, _altova_mi_altova_scriptFormatType2.end,  null, 				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[7] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_BPMNDiagramType.begin, _altova_mi_altova_BPMNDiagramType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[8] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_BPMNPlaneType.begin, _altova_mi_altova_BPMNPlaneType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[9] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_BPMNEdgeType.begin, _altova_mi_altova_BPMNEdgeType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[10] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_string2, _altova_mi_altova_bpmnElementType.begin, _altova_mi_altova_bpmnElementType.end,  null, 				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[11] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_waypointType.begin, _altova_mi_altova_waypointType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[12] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_BPMNShapeType.begin, _altova_mi_altova_BPMNShapeType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[13] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_string2, _altova_mi_altova_bpmnElementType2.begin, _altova_mi_altova_bpmnElementType2.end,  null, 				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[14] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_BoundsType.begin, _altova_mi_altova_BoundsType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[15] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_assignmentType.begin, _altova_mi_altova_assignmentType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[16] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_conditionExpressionType.begin, _altova_mi_altova_conditionExpressionType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[17] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_string2, _altova_mi_altova_typeType.begin, _altova_mi_altova_typeType.end,  null, 				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[18] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_dataInputType.begin, _altova_mi_altova_dataInputType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[19] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_string2, _altova_mi_altova_nameType.begin, _altova_mi_altova_nameType.end,  null, 				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[20] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_string2, _altova_mi_altova_idType.begin, _altova_mi_altova_idType.end,  null, 				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[21] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_dataInputAssociationType.begin, _altova_mi_altova_dataInputAssociationType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[22] = new TypeInfo( binder, _altova_ni, "", 0, _altova_mi_altova_targetRefType.begin, _altova_mi_altova_targetRefType.end,  null, 				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[23] = new TypeInfo( binder, _altova_ni, "", 0, _altova_mi_altova_sourceRefType.begin, _altova_mi_altova_sourceRefType.end,  null, 				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[24] = new TypeInfo( binder, _altova_ni, "", 0, _altova_mi_altova_dataInputRefsType.begin, _altova_mi_altova_dataInputRefsType.end,  null, 				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[25] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_string2, _altova_mi_altova_dataInputRefsType2.begin, _altova_mi_altova_dataInputRefsType2.end,  null, 				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[26] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_dataOutputType.begin, _altova_mi_altova_dataOutputType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[27] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_string2, _altova_mi_altova_nameType2.begin, _altova_mi_altova_nameType2.end,  null, 				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[28] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_string2, _altova_mi_altova_idType2.begin, _altova_mi_altova_idType2.end,  null, 				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[29] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_dataOutputAssociationType.begin, _altova_mi_altova_dataOutputAssociationType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[30] = new TypeInfo( binder, _altova_ni, "", 0, _altova_mi_altova_dataOutputRefsType.begin, _altova_mi_altova_dataOutputRefsType.end,  null, 				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[31] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_string2, _altova_mi_altova_dataOutputRefsType2.begin, _altova_mi_altova_dataOutputRefsType2.end,  null, 				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[32] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_definitionsType.begin, _altova_mi_altova_definitionsType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[33] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyURI, _altova_mi_altova_typeLanguageType.begin, _altova_mi_altova_typeLanguageType.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "enumeration", "http://www.java.com/javaTypes", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[34] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyURI, _altova_mi_altova_targetNamespaceType.begin, _altova_mi_altova_targetNamespaceType.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "enumeration", "http://www.jboss.org/drools", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[35] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_string2, _altova_mi_altova_idType3.begin, _altova_mi_altova_idType3.end,  null, 				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[36] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyURI, _altova_mi_altova_expressionLanguageType.begin, _altova_mi_altova_expressionLanguageType.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "enumeration", "http://www.mvel.org/2.0", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[37] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_processType.begin, _altova_mi_altova_processType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[38] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_endEventType.begin, _altova_mi_altova_endEventType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[39] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_string2, _altova_mi_altova_nameType3.begin, _altova_mi_altova_nameType3.end,  null, 				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[40] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_string2, _altova_mi_altova_idType4.begin, _altova_mi_altova_idType4.end,  null, 				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[41] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_exclusiveGatewayType.begin, _altova_mi_altova_exclusiveGatewayType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[42] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_string2, _altova_mi_altova_nameType4.begin, _altova_mi_altova_nameType4.end,  null, 				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[43] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_string2, _altova_mi_altova_idType5.begin, _altova_mi_altova_idType5.end,  null, 				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[44] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_string2, _altova_mi_altova_gatewayDirectionType.begin, _altova_mi_altova_gatewayDirectionType.end,  null, 				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[45] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_extensionElementsType.begin, _altova_mi_altova_extensionElementsType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[46] = new TypeInfo( binder, _altova_ni, "", 0, _altova_mi_altova_formalExpressionType.begin, _altova_mi_altova_formalExpressionType.end,  null, 				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[47] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_string2, _altova_mi_altova_formalExpressionType2.begin, _altova_mi_altova_formalExpressionType2.end,  null, 				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[48] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_inputSetType.begin, _altova_mi_altova_inputSetType.end,  null, 				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[49] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_ioSpecificationType.begin, _altova_mi_altova_ioSpecificationType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[50] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_outputSetType.begin, _altova_mi_altova_outputSetType.end,  null, 				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[51] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_potentialOwnerType.begin, _altova_mi_altova_potentialOwnerType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[52] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_resourceAssignmentExpressionType.begin, _altova_mi_altova_resourceAssignmentExpressionType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[53] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_sequenceFlowType.begin, _altova_mi_altova_sequenceFlowType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[54] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_string2, _altova_mi_altova_targetRefType2.begin, _altova_mi_altova_targetRefType2.end,  null, 				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[55] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_string2, _altova_mi_altova_sourceRefType2.begin, _altova_mi_altova_sourceRefType2.end,  null, 				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[56] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_string2, _altova_mi_altova_idType6.begin, _altova_mi_altova_idType6.end,  null, 				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[57] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_startEventType.begin, _altova_mi_altova_startEventType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[58] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_string2, _altova_mi_altova_nameType5.begin, _altova_mi_altova_nameType5.end,  null, 				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[59] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_string2, _altova_mi_altova_idType7.begin, _altova_mi_altova_idType7.end,  null, 				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[60] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_userTaskType.begin, _altova_mi_altova_userTaskType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[61] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_string2, _altova_mi_altova_nameType6.begin, _altova_mi_altova_nameType6.end,  null, 				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[62] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_string2, _altova_mi_altova_idType8.begin, _altova_mi_altova_idType8.end,  null, 				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[63] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_short2, _altova_mi_altova_yType.begin, _altova_mi_altova_yType.end,  null, 				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.IntegerFormatter );
			types[64] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_short2, _altova_mi_altova_xType.begin, _altova_mi_altova_xType.end,  null, 				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.IntegerFormatter );
			types[65] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_short2, _altova_mi_altova_yType2.begin, _altova_mi_altova_yType2.end,  null, 				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.IntegerFormatter );
			types[66] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_byte2, _altova_mi_altova_xType2.begin, _altova_mi_altova_xType2.end,  null, 				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.IntegerFormatter );
			types[67] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_byte2, _altova_mi_altova_widthType.begin, _altova_mi_altova_widthType.end,  null, 				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.IntegerFormatter );
			types[68] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_byte2, _altova_mi_altova_heightType.begin, _altova_mi_altova_heightType.end,  null, 				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.IntegerFormatter );
			types[69] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_string2, _altova_mi_altova_processTypeType.begin, _altova_mi_altova_processTypeType.end,  
				new FacetInfo[]
				{
					new FacetInfo (com.migration.xml.XsValidation.facetCheck_string_enumeration, "enumeration", "Private", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.AnySimpleTypeFormatter );



			types[70] = new TypeInfo( binder, _altova_ni_xs, "ENTITIES", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_ENTITIES.begin, _altova_mi_xs_altova_ENTITIES.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
					new FacetInfo (null, "minLength", "1", 1 ), 
				},
				WhitespaceType.Whitespace_Collapse, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[71] = new TypeInfo( binder, _altova_ni_xs, "ENTITY", _altova_ti_xs_altova_NCName, _altova_mi_xs_altova_ENTITY.begin, _altova_mi_xs_altova_ENTITY.end,  null, 				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[72] = new TypeInfo( binder, _altova_ni_xs, "ID", _altova_ti_xs_altova_NCName, _altova_mi_xs_altova_ID.begin, _altova_mi_xs_altova_ID.end,  null, 				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[73] = new TypeInfo( binder, _altova_ni_xs, "IDREF", _altova_ti_xs_altova_NCName, _altova_mi_xs_altova_IDREF.begin, _altova_mi_xs_altova_IDREF.end,  null, 				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[74] = new TypeInfo( binder, _altova_ni_xs, "IDREFS", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_IDREFS.begin, _altova_mi_xs_altova_IDREFS.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
					new FacetInfo (null, "minLength", "1", 1 ), 
				},
				WhitespaceType.Whitespace_Collapse, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[75] = new TypeInfo( binder, _altova_ni_xs, "NCName", _altova_ti_xs_altova_Name, _altova_mi_xs_altova_NCName.begin, _altova_mi_xs_altova_NCName.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "pattern", "[\\i-[:]][\\c-[:]]*", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[76] = new TypeInfo( binder, _altova_ni_xs, "NMTOKEN", _altova_ti_xs_altova_token, _altova_mi_xs_altova_NMTOKEN.begin, _altova_mi_xs_altova_NMTOKEN.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "pattern", "\\c+", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[77] = new TypeInfo( binder, _altova_ni_xs, "NMTOKENS", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_NMTOKENS.begin, _altova_mi_xs_altova_NMTOKENS.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
					new FacetInfo (null, "minLength", "1", 1 ), 
					new FacetInfo (null, "pattern", "\\c+", 0 ), 
					new FacetInfo (null, "pattern", "\\c+", 0 ), 
				},
				WhitespaceType.Whitespace_Collapse, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[78] = new TypeInfo( binder, _altova_ni_xs, "NOTATION", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_NOTATION.begin, _altova_mi_xs_altova_NOTATION.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[79] = new TypeInfo( binder, _altova_ni_xs, "Name", _altova_ti_xs_altova_token, _altova_mi_xs_altova_Name.begin, _altova_mi_xs_altova_Name.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "pattern", "\\i\\c*", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[80] = new TypeInfo( binder, _altova_ni_xs, "QName", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_QName.begin, _altova_mi_xs_altova_QName.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[81] = new TypeInfo( binder, _altova_ni_xs, "anySimpleType", 0, _altova_mi_xs_altova_anySimpleType.begin, _altova_mi_xs_altova_anySimpleType.end,  null, 				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[82] = new TypeInfo( binder, _altova_ni_xs, "anyType", 0, _altova_mi_xs_altova_anyType.begin, _altova_mi_xs_altova_anyType.end,  null, 				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[83] = new TypeInfo( binder, _altova_ni_xs, "anyURI", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_anyURI.begin, _altova_mi_xs_altova_anyURI.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[84] = new TypeInfo( binder, _altova_ni_xs, "base64Binary", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_base64Binary.begin, _altova_mi_xs_altova_base64Binary.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[85] = new TypeInfo( binder, _altova_ni_xs, "boolean", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_boolean2.begin, _altova_mi_xs_altova_boolean2.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[86] = new TypeInfo( binder, _altova_ni_xs, "byte", _altova_ti_xs_altova_short2, _altova_mi_xs_altova_byte2.begin, _altova_mi_xs_altova_byte2.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "minInclusive", "-128", 0 ), 
					new FacetInfo (null, "maxInclusive", "127", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.IntegerFormatter );
			types[87] = new TypeInfo( binder, _altova_ni_xs, "date", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_date.begin, _altova_mi_xs_altova_date.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.migration.xml.Xs.DateFormatter );
			types[88] = new TypeInfo( binder, _altova_ni_xs, "dateTime", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_dateTime.begin, _altova_mi_xs_altova_dateTime.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.migration.xml.Xs.DateTimeFormatter );
			types[89] = new TypeInfo( binder, _altova_ni_xs, "decimal", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_decimal.begin, _altova_mi_xs_altova_decimal.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.migration.xml.Xs.DecimalFormatter );
			types[90] = new TypeInfo( binder, _altova_ni_xs, "double", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_double2.begin, _altova_mi_xs_altova_double2.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.migration.xml.Xs.DoubleFormatter );
			types[91] = new TypeInfo( binder, _altova_ni_xs, "duration", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_duration.begin, _altova_mi_xs_altova_duration.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.migration.xml.Xs.DurationFormatter );
			types[92] = new TypeInfo( binder, _altova_ni_xs, "float", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_float2.begin, _altova_mi_xs_altova_float2.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.migration.xml.Xs.DoubleFormatter );
			types[93] = new TypeInfo( binder, _altova_ni_xs, "gDay", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_gDay.begin, _altova_mi_xs_altova_gDay.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.migration.xml.Xs.GDayFormatter );
			types[94] = new TypeInfo( binder, _altova_ni_xs, "gMonth", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_gMonth.begin, _altova_mi_xs_altova_gMonth.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.migration.xml.Xs.GMonthFormatter );
			types[95] = new TypeInfo( binder, _altova_ni_xs, "gMonthDay", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_gMonthDay.begin, _altova_mi_xs_altova_gMonthDay.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.migration.xml.Xs.GMonthDayFormatter );
			types[96] = new TypeInfo( binder, _altova_ni_xs, "gYear", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_gYear.begin, _altova_mi_xs_altova_gYear.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.migration.xml.Xs.GYearFormatter );
			types[97] = new TypeInfo( binder, _altova_ni_xs, "gYearMonth", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_gYearMonth.begin, _altova_mi_xs_altova_gYearMonth.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.migration.xml.Xs.GYearMonthFormatter );
			types[98] = new TypeInfo( binder, _altova_ni_xs, "hexBinary", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_hexBinary.begin, _altova_mi_xs_altova_hexBinary.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.migration.xml.Xs.HexBinaryFormatter );
			types[99] = new TypeInfo( binder, _altova_ni_xs, "int", _altova_ti_xs_altova_long2, _altova_mi_xs_altova_int2.begin, _altova_mi_xs_altova_int2.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "minInclusive", "-2147483648", 0 ), 
					new FacetInfo (null, "maxInclusive", "2147483647", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.IntegerFormatter );
			types[100] = new TypeInfo( binder, _altova_ni_xs, "integer", _altova_ti_xs_altova_decimal, _altova_mi_xs_altova_integer.begin, _altova_mi_xs_altova_integer.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "fractionDigits", "0", 0 ), 
					new FacetInfo (null, "pattern", "[\\-+]?[0-9]+", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.IntegerFormatter );
			types[101] = new TypeInfo( binder, _altova_ni_xs, "language", _altova_ti_xs_altova_token, _altova_mi_xs_altova_language.begin, _altova_mi_xs_altova_language.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "pattern", "[a-zA-Z]{1,8}(-[a-zA-Z0-9]{1,8})*", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[102] = new TypeInfo( binder, _altova_ni_xs, "long", _altova_ti_xs_altova_integer, _altova_mi_xs_altova_long2.begin, _altova_mi_xs_altova_long2.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "minInclusive", "-9223372036854775808", 0 ), 
					new FacetInfo (null, "maxInclusive", "9223372036854775807", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.IntegerFormatter );
			types[103] = new TypeInfo( binder, _altova_ni_xs, "negativeInteger", _altova_ti_xs_altova_nonPositiveInteger, _altova_mi_xs_altova_negativeInteger.begin, _altova_mi_xs_altova_negativeInteger.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "maxInclusive", "-1", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.IntegerFormatter );
			types[104] = new TypeInfo( binder, _altova_ni_xs, "nonNegativeInteger", _altova_ti_xs_altova_integer, _altova_mi_xs_altova_nonNegativeInteger.begin, _altova_mi_xs_altova_nonNegativeInteger.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "minInclusive", "0", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.IntegerFormatter );
			types[105] = new TypeInfo( binder, _altova_ni_xs, "nonPositiveInteger", _altova_ti_xs_altova_integer, _altova_mi_xs_altova_nonPositiveInteger.begin, _altova_mi_xs_altova_nonPositiveInteger.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "maxInclusive", "0", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.IntegerFormatter );
			types[106] = new TypeInfo( binder, _altova_ni_xs, "normalizedString", _altova_ti_xs_altova_string2, _altova_mi_xs_altova_normalizedString.begin, _altova_mi_xs_altova_normalizedString.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "replace", 0 ),
				},
				WhitespaceType.Whitespace_Replace, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[107] = new TypeInfo( binder, _altova_ni_xs, "positiveInteger", _altova_ti_xs_altova_nonNegativeInteger, _altova_mi_xs_altova_positiveInteger.begin, _altova_mi_xs_altova_positiveInteger.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "minInclusive", "1", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.IntegerFormatter );
			types[108] = new TypeInfo( binder, _altova_ni_xs, "short", _altova_ti_xs_altova_int2, _altova_mi_xs_altova_short2.begin, _altova_mi_xs_altova_short2.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "minInclusive", "-32768", 0 ), 
					new FacetInfo (null, "maxInclusive", "32767", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.IntegerFormatter );
			types[109] = new TypeInfo( binder, _altova_ni_xs, "string", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_string2.begin, _altova_mi_xs_altova_string2.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "preserve", 0 ),
				},
				WhitespaceType.Whitespace_Preserve, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[110] = new TypeInfo( binder, _altova_ni_xs, "time", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_time.begin, _altova_mi_xs_altova_time.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.migration.xml.Xs.TimeFormatter );
			types[111] = new TypeInfo( binder, _altova_ni_xs, "token", _altova_ti_xs_altova_normalizedString, _altova_mi_xs_altova_token.begin, _altova_mi_xs_altova_token.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.migration.xml.Xs.AnySimpleTypeFormatter );
			types[112] = new TypeInfo( binder, _altova_ni_xs, "unsignedByte", _altova_ti_xs_altova_unsignedShort, _altova_mi_xs_altova_unsignedByte.begin, _altova_mi_xs_altova_unsignedByte.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "maxInclusive", "255", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.IntegerFormatter );
			types[113] = new TypeInfo( binder, _altova_ni_xs, "unsignedInt", _altova_ti_xs_altova_unsignedLong, _altova_mi_xs_altova_unsignedInt.begin, _altova_mi_xs_altova_unsignedInt.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "maxInclusive", "4294967295", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.IntegerFormatter );
			types[114] = new TypeInfo( binder, _altova_ni_xs, "unsignedLong", _altova_ti_xs_altova_nonNegativeInteger, _altova_mi_xs_altova_unsignedLong.begin, _altova_mi_xs_altova_unsignedLong.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "maxInclusive", "18446744073709551615", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.IntegerFormatter );
			types[115] = new TypeInfo( binder, _altova_ni_xs, "unsignedShort", _altova_ti_xs_altova_unsignedInt, _altova_mi_xs_altova_unsignedShort.begin, _altova_mi_xs_altova_unsignedShort.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "maxInclusive", "65535", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.IntegerFormatter );
			types[116] = new TypeInfo( binder, _altova_ni_xs, "", 0, _altova_mi_xs_altova_stringType.begin, _altova_mi_xs_altova_stringType.end,  null, 				WhitespaceType.Whitespace_Unknown, com.migration.xml.Xs.AnySimpleTypeFormatter );

		}

		public TypeInfo[] createTypes(InfoBinderInterface binder) {

			TypeInfo types[] = new TypeInfo[117];

			initTypes0(binder, types);
			
			return types;

		}
	}

	// Array of all members
	public static final MemberInfo members[] = new MemberInfoCreator().createMembers(binder);

	private static class MemberInfoCreator
	{
		private void initMembers0(InfoBinderInterface binder, MemberInfo[] members) {
			members[0] = new MemberInfo (binder, "http://www.jboss.org/drools", "onEntry-script", _altova_ti_altova_jbpm5v22, _altova_ti_altova_onEntry_scriptType, 0, 0, 1);
			members[1] = new MemberInfo (binder, "http://www.jboss.org/drools", "onExit-script", _altova_ti_altova_jbpm5v22, _altova_ti_altova_onExit_scriptType, 0, 0, 1);
			members[2] = new MemberInfo (binder, "http://www.jboss.org/drools", "script", _altova_ti_altova_jbpm5v22, _altova_ti_altova_scriptType, 0, 0, 1);
			members[3] = new MemberInfo (binder, "http://www.omg.org/spec/BPMN/20100524/DI", "BPMNDiagram", _altova_ti_altova_jbpm5v22, _altova_ti_altova_BPMNDiagramType, 0, 0, 1);
			members[4] = new MemberInfo (binder, "http://www.omg.org/spec/BPMN/20100524/DI", "BPMNEdge", _altova_ti_altova_jbpm5v22, _altova_ti_altova_BPMNEdgeType, 0, 0, 1);
			members[5] = new MemberInfo (binder, "http://www.omg.org/spec/BPMN/20100524/DI", "BPMNPlane", _altova_ti_altova_jbpm5v22, _altova_ti_altova_BPMNPlaneType, 0, 0, 1);
			members[6] = new MemberInfo (binder, "http://www.omg.org/spec/BPMN/20100524/DI", "BPMNShape", _altova_ti_altova_jbpm5v22, _altova_ti_altova_BPMNShapeType, 0, 0, 1);
			members[7] = new MemberInfo (binder, "http://www.omg.org/spec/BPMN/20100524/MODEL", "assignment", _altova_ti_altova_jbpm5v22, _altova_ti_altova_assignmentType, 0, 0, 1);
			members[8] = new MemberInfo (binder, "http://www.omg.org/spec/BPMN/20100524/MODEL", "conditionExpression", _altova_ti_altova_jbpm5v22, _altova_ti_altova_conditionExpressionType, 0, 0, 1);
			members[9] = new MemberInfo (binder, "http://www.omg.org/spec/BPMN/20100524/MODEL", "dataInput", _altova_ti_altova_jbpm5v22, _altova_ti_altova_dataInputType, 0, 0, 1);
			members[10] = new MemberInfo (binder, "http://www.omg.org/spec/BPMN/20100524/MODEL", "dataInputAssociation", _altova_ti_altova_jbpm5v22, _altova_ti_altova_dataInputAssociationType, 0, 0, 1);
			members[11] = new MemberInfo (binder, "http://www.omg.org/spec/BPMN/20100524/MODEL", "dataInputRefs", _altova_ti_altova_jbpm5v22, _altova_ti_altova_dataInputRefsType, 0, 0, 1);
			members[12] = new MemberInfo (binder, "http://www.omg.org/spec/BPMN/20100524/MODEL", "dataOutput", _altova_ti_altova_jbpm5v22, _altova_ti_altova_dataOutputType, 0, 0, 1);
			members[13] = new MemberInfo (binder, "http://www.omg.org/spec/BPMN/20100524/MODEL", "dataOutputAssociation", _altova_ti_altova_jbpm5v22, _altova_ti_altova_dataOutputAssociationType, 0, 0, 1);
			members[14] = new MemberInfo (binder, "http://www.omg.org/spec/BPMN/20100524/MODEL", "dataOutputRefs", _altova_ti_altova_jbpm5v22, _altova_ti_altova_dataOutputRefsType, 0, 0, 1);
			members[15] = new MemberInfo (binder, "http://www.omg.org/spec/BPMN/20100524/MODEL", "definitions", _altova_ti_altova_jbpm5v22, _altova_ti_altova_definitionsType, 0, 0, 1);
			members[16] = new MemberInfo (binder, "http://www.omg.org/spec/BPMN/20100524/MODEL", "endEvent", _altova_ti_altova_jbpm5v22, _altova_ti_altova_endEventType, 0, 0, 1);
			members[17] = new MemberInfo (binder, "http://www.omg.org/spec/BPMN/20100524/MODEL", "exclusiveGateway", _altova_ti_altova_jbpm5v22, _altova_ti_altova_exclusiveGatewayType, 0, 0, 1);
			members[18] = new MemberInfo (binder, "http://www.omg.org/spec/BPMN/20100524/MODEL", "extensionElements", _altova_ti_altova_jbpm5v22, _altova_ti_altova_extensionElementsType, 0, 0, 1);
			members[19] = new MemberInfo (binder, "http://www.omg.org/spec/BPMN/20100524/MODEL", "formalExpression", _altova_ti_altova_jbpm5v22, _altova_ti_altova_formalExpressionType, 0, 0, 1);
			members[20] = new MemberInfo (binder, "http://www.omg.org/spec/BPMN/20100524/MODEL", "from", _altova_ti_altova_jbpm5v22, _altova_ti_xs_altova_stringType, 0, 0, 1);
			members[21] = new MemberInfo (binder, "http://www.omg.org/spec/BPMN/20100524/MODEL", "inputSet", _altova_ti_altova_jbpm5v22, _altova_ti_altova_inputSetType, 0, 0, 1);
			members[22] = new MemberInfo (binder, "http://www.omg.org/spec/BPMN/20100524/MODEL", "ioSpecification", _altova_ti_altova_jbpm5v22, _altova_ti_altova_ioSpecificationType, 0, 0, 1);
			members[23] = new MemberInfo (binder, "http://www.omg.org/spec/BPMN/20100524/MODEL", "outputSet", _altova_ti_altova_jbpm5v22, _altova_ti_altova_outputSetType, 0, 0, 1);
			members[24] = new MemberInfo (binder, "http://www.omg.org/spec/BPMN/20100524/MODEL", "potentialOwner", _altova_ti_altova_jbpm5v22, _altova_ti_altova_potentialOwnerType, 0, 0, 1);
			members[25] = new MemberInfo (binder, "http://www.omg.org/spec/BPMN/20100524/MODEL", "process", _altova_ti_altova_jbpm5v22, _altova_ti_altova_processType, 0, 0, 1);
			members[26] = new MemberInfo (binder, "http://www.omg.org/spec/BPMN/20100524/MODEL", "resourceAssignmentExpression", _altova_ti_altova_jbpm5v22, _altova_ti_altova_resourceAssignmentExpressionType, 0, 0, 1);
			members[27] = new MemberInfo (binder, "http://www.omg.org/spec/BPMN/20100524/MODEL", "sequenceFlow", _altova_ti_altova_jbpm5v22, _altova_ti_altova_sequenceFlowType, 0, 0, 1);
			members[28] = new MemberInfo (binder, "http://www.omg.org/spec/BPMN/20100524/MODEL", "sourceRef", _altova_ti_altova_jbpm5v22, _altova_ti_altova_sourceRefType, 0, 0, 1);
			members[29] = new MemberInfo (binder, "http://www.omg.org/spec/BPMN/20100524/MODEL", "startEvent", _altova_ti_altova_jbpm5v22, _altova_ti_altova_startEventType, 0, 0, 1);
			members[30] = new MemberInfo (binder, "http://www.omg.org/spec/BPMN/20100524/MODEL", "targetRef", _altova_ti_altova_jbpm5v22, _altova_ti_altova_targetRefType, 0, 0, 1);
			members[31] = new MemberInfo (binder, "http://www.omg.org/spec/BPMN/20100524/MODEL", "to", _altova_ti_altova_jbpm5v22, _altova_ti_xs_altova_stringType, 0, 0, 1);
			members[32] = new MemberInfo (binder, "http://www.omg.org/spec/BPMN/20100524/MODEL", "userTask", _altova_ti_altova_jbpm5v22, _altova_ti_altova_userTaskType, 0, 0, 1);
			members[33] = new MemberInfo (binder, "http://www.omg.org/spec/DD/20100524/DC", "Bounds", _altova_ti_altova_jbpm5v22, _altova_ti_altova_BoundsType, 0, 0, 1);
			members[34] = new MemberInfo (binder, "http://www.omg.org/spec/DD/20100524/DI", "waypoint", _altova_ti_altova_jbpm5v22, _altova_ti_altova_waypointType, 0, 0, 1);

			members[35] = new MemberInfo (binder, "", "scriptFormat", _altova_ti_altova_onEntry_scriptType, _altova_ti_altova_scriptFormatType, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);
			members[36] = new MemberInfo (binder, "http://www.jboss.org/drools", "script", _altova_ti_altova_onEntry_scriptType, _altova_ti_altova_scriptType, 0, 1, 1);

			members[37] = new MemberInfo (binder, "", "", _altova_ti_altova_scriptType, _altova_ti_xs_altova_anySimpleType, 0|MemberInfo.IS_ATTRIBUTE, 0, -1);

			members[38] = new MemberInfo (binder, "", "scriptFormat", _altova_ti_altova_onExit_scriptType, _altova_ti_altova_scriptFormatType2, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);
			members[39] = new MemberInfo (binder, "http://www.jboss.org/drools", "script", _altova_ti_altova_onExit_scriptType, _altova_ti_altova_scriptType, 0, 1, 1);

			members[40] = new MemberInfo (binder, "http://www.omg.org/spec/BPMN/20100524/DI", "BPMNPlane", _altova_ti_altova_BPMNDiagramType, _altova_ti_altova_BPMNPlaneType, 0, 1, 1);

			members[41] = new MemberInfo (binder, "", "bpmnElement", _altova_ti_altova_BPMNPlaneType, _altova_ti_xs_altova_string2, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);
			members[42] = new MemberInfo (binder, "http://www.omg.org/spec/BPMN/20100524/DI", "BPMNShape", _altova_ti_altova_BPMNPlaneType, _altova_ti_altova_BPMNShapeType, 0, 1, -1);
			members[43] = new MemberInfo (binder, "http://www.omg.org/spec/BPMN/20100524/DI", "BPMNEdge", _altova_ti_altova_BPMNPlaneType, _altova_ti_altova_BPMNEdgeType, 0, 1, -1);

			members[44] = new MemberInfo (binder, "", "bpmnElement", _altova_ti_altova_BPMNEdgeType, _altova_ti_altova_bpmnElementType, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);
			members[45] = new MemberInfo (binder, "http://www.omg.org/spec/DD/20100524/DI", "waypoint", _altova_ti_altova_BPMNEdgeType, _altova_ti_altova_waypointType, 0, 1, -1);

			members[46] = new MemberInfo (binder, "", "y", _altova_ti_altova_waypointType, _altova_ti_altova_yType, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);
			members[47] = new MemberInfo (binder, "", "x", _altova_ti_altova_waypointType, _altova_ti_altova_xType, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);

			members[48] = new MemberInfo (binder, "", "bpmnElement", _altova_ti_altova_BPMNShapeType, _altova_ti_altova_bpmnElementType2, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);
			members[49] = new MemberInfo (binder, "http://www.omg.org/spec/DD/20100524/DC", "Bounds", _altova_ti_altova_BPMNShapeType, _altova_ti_altova_BoundsType, 0, 1, 1);

			members[50] = new MemberInfo (binder, "", "y", _altova_ti_altova_BoundsType, _altova_ti_altova_yType2, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);
			members[51] = new MemberInfo (binder, "", "x", _altova_ti_altova_BoundsType, _altova_ti_altova_xType2, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);
			members[52] = new MemberInfo (binder, "", "width", _altova_ti_altova_BoundsType, _altova_ti_altova_widthType, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);
			members[53] = new MemberInfo (binder, "", "height", _altova_ti_altova_BoundsType, _altova_ti_altova_heightType, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);

			members[54] = new MemberInfo (binder, "http://www.omg.org/spec/BPMN/20100524/MODEL", "from", _altova_ti_altova_assignmentType, _altova_ti_xs_altova_stringType, 0, 1, 1);
			members[55] = new MemberInfo (binder, "http://www.omg.org/spec/BPMN/20100524/MODEL", "to", _altova_ti_altova_assignmentType, _altova_ti_xs_altova_stringType, 0, 1, 1);

			members[56] = new MemberInfo (binder, "", "type", _altova_ti_altova_conditionExpressionType, _altova_ti_altova_typeType, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);

			members[57] = new MemberInfo (binder, "", "name", _altova_ti_altova_dataInputType, _altova_ti_altova_nameType, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);
			members[58] = new MemberInfo (binder, "", "id", _altova_ti_altova_dataInputType, _altova_ti_altova_idType, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);

			members[59] = new MemberInfo (binder, "http://www.omg.org/spec/BPMN/20100524/MODEL", "targetRef", _altova_ti_altova_dataInputAssociationType, _altova_ti_altova_targetRefType, 0, 0, 1);
			members[60] = new MemberInfo (binder, "http://www.omg.org/spec/BPMN/20100524/MODEL", "assignment", _altova_ti_altova_dataInputAssociationType, _altova_ti_altova_assignmentType, 0, 0, 1);
			members[61] = new MemberInfo (binder, "http://www.omg.org/spec/BPMN/20100524/MODEL", "sourceRef", _altova_ti_altova_dataInputAssociationType, _altova_ti_altova_sourceRefType, 0, 0, 1);

			members[62] = new MemberInfo (binder, "", "", _altova_ti_altova_targetRefType, _altova_ti_xs_altova_anySimpleType, 0|MemberInfo.IS_ATTRIBUTE, 0, -1);

			members[63] = new MemberInfo (binder, "", "", _altova_ti_altova_sourceRefType, _altova_ti_xs_altova_anySimpleType, 0|MemberInfo.IS_ATTRIBUTE, 0, -1);

			members[64] = new MemberInfo (binder, "", "", _altova_ti_altova_dataInputRefsType, _altova_ti_altova_dataInputRefsType2, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);

			members[65] = new MemberInfo (binder, "", "name", _altova_ti_altova_dataOutputType, _altova_ti_altova_nameType2, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);
			members[66] = new MemberInfo (binder, "", "id", _altova_ti_altova_dataOutputType, _altova_ti_altova_idType2, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);

			members[67] = new MemberInfo (binder, "http://www.omg.org/spec/BPMN/20100524/MODEL", "sourceRef", _altova_ti_altova_dataOutputAssociationType, _altova_ti_altova_sourceRefType, 0, 1, 1);
			members[68] = new MemberInfo (binder, "http://www.omg.org/spec/BPMN/20100524/MODEL", "targetRef", _altova_ti_altova_dataOutputAssociationType, _altova_ti_altova_targetRefType, 0, 1, 1);

			members[69] = new MemberInfo (binder, "", "", _altova_ti_altova_dataOutputRefsType, _altova_ti_altova_dataOutputRefsType2, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);

			members[70] = new MemberInfo (binder, "", "typeLanguage", _altova_ti_altova_definitionsType, _altova_ti_altova_typeLanguageType, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);
			members[71] = new MemberInfo (binder, "", "targetNamespace", _altova_ti_altova_definitionsType, _altova_ti_altova_targetNamespaceType, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);
			members[72] = new MemberInfo (binder, "", "id", _altova_ti_altova_definitionsType, _altova_ti_altova_idType3, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);
			members[73] = new MemberInfo (binder, "", "expressionLanguage", _altova_ti_altova_definitionsType, _altova_ti_altova_expressionLanguageType, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);
			members[74] = new MemberInfo (binder, "http://www.omg.org/spec/BPMN/20100524/MODEL", "process", _altova_ti_altova_definitionsType, _altova_ti_altova_processType, 0, 1, 1);
			members[75] = new MemberInfo (binder, "http://www.omg.org/spec/BPMN/20100524/DI", "BPMNDiagram", _altova_ti_altova_definitionsType, _altova_ti_altova_BPMNDiagramType, 0, 1, 1);

			members[76] = new MemberInfo (binder, "http://www.jboss.org/drools", "packageName", _altova_ti_altova_processType, _altova_ti_xs_altova_string2, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);
			members[77] = new MemberInfo (binder, "", "processType", _altova_ti_altova_processType, _altova_ti_altova_processTypeType, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);
			members[78] = new MemberInfo (binder, "", "name", _altova_ti_altova_processType, _altova_ti_xs_altova_string2, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);
			members[79] = new MemberInfo (binder, "", "isExecutable", _altova_ti_altova_processType, _altova_ti_xs_altova_boolean2, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);
			members[80] = new MemberInfo (binder, "", "id", _altova_ti_altova_processType, _altova_ti_xs_altova_string2, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);
			members[81] = new MemberInfo (binder, "http://www.omg.org/spec/BPMN/20100524/MODEL", "startEvent", _altova_ti_altova_processType, _altova_ti_altova_startEventType, 0, 1, 1);
			members[82] = new MemberInfo (binder, "http://www.omg.org/spec/BPMN/20100524/MODEL", "userTask", _altova_ti_altova_processType, _altova_ti_altova_userTaskType, 0, 4, -1);
			members[83] = new MemberInfo (binder, "http://www.omg.org/spec/BPMN/20100524/MODEL", "exclusiveGateway", _altova_ti_altova_processType, _altova_ti_altova_exclusiveGatewayType, 0, 3, -1);
			members[84] = new MemberInfo (binder, "http://www.omg.org/spec/BPMN/20100524/MODEL", "endEvent", _altova_ti_altova_processType, _altova_ti_altova_endEventType, 0, 1, 1);
			members[85] = new MemberInfo (binder, "http://www.omg.org/spec/BPMN/20100524/MODEL", "sequenceFlow", _altova_ti_altova_processType, _altova_ti_altova_sequenceFlowType, 0, 1, -1);

			members[86] = new MemberInfo (binder, "", "name", _altova_ti_altova_endEventType, _altova_ti_altova_nameType3, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);
			members[87] = new MemberInfo (binder, "", "id", _altova_ti_altova_endEventType, _altova_ti_altova_idType4, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);

			members[88] = new MemberInfo (binder, "", "name", _altova_ti_altova_exclusiveGatewayType, _altova_ti_altova_nameType4, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);
			members[89] = new MemberInfo (binder, "", "id", _altova_ti_altova_exclusiveGatewayType, _altova_ti_altova_idType5, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);
			members[90] = new MemberInfo (binder, "", "gatewayDirection", _altova_ti_altova_exclusiveGatewayType, _altova_ti_altova_gatewayDirectionType, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);

			members[91] = new MemberInfo (binder, "http://www.jboss.org/drools", "onEntry-script", _altova_ti_altova_extensionElementsType, _altova_ti_altova_onEntry_scriptType, 0, 1, 1);
			members[92] = new MemberInfo (binder, "http://www.jboss.org/drools", "onExit-script", _altova_ti_altova_extensionElementsType, _altova_ti_altova_onExit_scriptType, 0, 1, 1);

			members[93] = new MemberInfo (binder, "", "", _altova_ti_altova_formalExpressionType, _altova_ti_altova_formalExpressionType2, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);

			members[94] = new MemberInfo (binder, "", "", _altova_ti_altova_inputSetType, _altova_ti_xs_altova_anySimpleType, 0|MemberInfo.IS_ATTRIBUTE, 0, -1);
			members[95] = new MemberInfo (binder, "http://www.omg.org/spec/BPMN/20100524/MODEL", "dataInputRefs", _altova_ti_altova_inputSetType, _altova_ti_altova_dataInputRefsType, 0, 0, -1);

			members[96] = new MemberInfo (binder, "http://www.omg.org/spec/BPMN/20100524/MODEL", "inputSet", _altova_ti_altova_ioSpecificationType, _altova_ti_altova_inputSetType, 0, 0, 1);
			members[97] = new MemberInfo (binder, "http://www.omg.org/spec/BPMN/20100524/MODEL", "outputSet", _altova_ti_altova_ioSpecificationType, _altova_ti_altova_outputSetType, 0, 0, 1);
			members[98] = new MemberInfo (binder, "http://www.omg.org/spec/BPMN/20100524/MODEL", "dataInput", _altova_ti_altova_ioSpecificationType, _altova_ti_altova_dataInputType, 0, 0, -1);
			members[99] = new MemberInfo (binder, "http://www.omg.org/spec/BPMN/20100524/MODEL", "dataOutput", _altova_ti_altova_ioSpecificationType, _altova_ti_altova_dataOutputType, 0, 0, 1);

			members[100] = new MemberInfo (binder, "", "", _altova_ti_altova_outputSetType, _altova_ti_xs_altova_anySimpleType, 0|MemberInfo.IS_ATTRIBUTE, 0, -1);
			members[101] = new MemberInfo (binder, "http://www.omg.org/spec/BPMN/20100524/MODEL", "dataOutputRefs", _altova_ti_altova_outputSetType, _altova_ti_altova_dataOutputRefsType, 0, 0, -1);

			members[102] = new MemberInfo (binder, "http://www.omg.org/spec/BPMN/20100524/MODEL", "resourceAssignmentExpression", _altova_ti_altova_potentialOwnerType, _altova_ti_altova_resourceAssignmentExpressionType, 0, 1, 1);

			members[103] = new MemberInfo (binder, "http://www.omg.org/spec/BPMN/20100524/MODEL", "formalExpression", _altova_ti_altova_resourceAssignmentExpressionType, _altova_ti_altova_formalExpressionType, 0, 1, 1);

			members[104] = new MemberInfo (binder, "", "targetRef", _altova_ti_altova_sequenceFlowType, _altova_ti_altova_targetRefType2, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);
			members[105] = new MemberInfo (binder, "", "sourceRef", _altova_ti_altova_sequenceFlowType, _altova_ti_altova_sourceRefType2, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);
			members[106] = new MemberInfo (binder, "", "id", _altova_ti_altova_sequenceFlowType, _altova_ti_altova_idType6, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);
			members[107] = new MemberInfo (binder, "http://www.omg.org/spec/BPMN/20100524/MODEL", "conditionExpression", _altova_ti_altova_sequenceFlowType, _altova_ti_altova_conditionExpressionType, 0, 0, 1);

			members[108] = new MemberInfo (binder, "", "name", _altova_ti_altova_startEventType, _altova_ti_altova_nameType5, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);
			members[109] = new MemberInfo (binder, "", "id", _altova_ti_altova_startEventType, _altova_ti_altova_idType7, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);

			members[110] = new MemberInfo (binder, "", "name", _altova_ti_altova_userTaskType, _altova_ti_altova_nameType6, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);
			members[111] = new MemberInfo (binder, "", "id", _altova_ti_altova_userTaskType, _altova_ti_altova_idType8, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);
			members[112] = new MemberInfo (binder, "http://www.omg.org/spec/BPMN/20100524/MODEL", "ioSpecification", _altova_ti_altova_userTaskType, _altova_ti_altova_ioSpecificationType, 0, 0, 1);
			members[113] = new MemberInfo (binder, "http://www.omg.org/spec/BPMN/20100524/MODEL", "dataInputAssociation", _altova_ti_altova_userTaskType, _altova_ti_altova_dataInputAssociationType, 0, 0, -1);
			members[114] = new MemberInfo (binder, "http://www.omg.org/spec/BPMN/20100524/MODEL", "extensionElements", _altova_ti_altova_userTaskType, _altova_ti_altova_extensionElementsType, 0, 0, 1);
			members[115] = new MemberInfo (binder, "http://www.omg.org/spec/BPMN/20100524/MODEL", "dataOutputAssociation", _altova_ti_altova_userTaskType, _altova_ti_altova_dataOutputAssociationType, 0, 0, 1);
			members[116] = new MemberInfo (binder, "http://www.omg.org/spec/BPMN/20100524/MODEL", "potentialOwner", _altova_ti_altova_userTaskType, _altova_ti_altova_potentialOwnerType, 0, 0, 1);

			members[117] = new MemberInfo (binder, "", "", _altova_ti_xs_altova_anyType, _altova_ti_xs_altova_anySimpleType, 0|MemberInfo.IS_ATTRIBUTE, 0, -1);

			members[118] = new MemberInfo (binder, "", "", _altova_ti_xs_altova_stringType, _altova_ti_xs_altova_string2, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);

		}

		public MemberInfo[] createMembers(InfoBinderInterface binder) {

			MemberInfo members[] = new MemberInfo[119];

			initMembers0(binder, members);
			
			return members;

		}
	}
}
