/**
 * jbpm3processdocgpdTest.java
 *
 * This file was generated by XMLSpy 2009sp1 Enterprise Edition.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the XMLSpy Documentation for further details.
 * http://www.altova.com/xmlspy
 */

package com.jbpm3processdocgpdTest;

import java.io.PrintWriter;
import java.io.StringWriter;

import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;

import com.jbpm3processdocgpd.*;

public class jbpm3processdocgpdTest {
	protected static void example() throws Exception {
		//
		// TODO:
		// Insert your code here...
		//
		// Example code to create and save a structure:
		// com.jbpm3processdocgpd.jbpm3processdocgpd2 doc = com.jbpm3processdocgpd.jbpm3processdocgpd2.createDocument();
		// 
		// com.jbpm3processdocgpd.root_containerType root = doc.root_container.append();
		// 
		// ...
		// doc.saveToFile("jbpm3processdocgpd1.xml", true);
		//
		// Example code to load and save a structure:
		// com.jbpm3processdocgpd.jbpm3processdocgpd2 doc = com.jbpm3processdocgpd.jbpm3processdocgpd2.loadFromFile("jbpm3processdocgpd1.xml");
		// 
		// com.jbpm3processdocgpd.root_containerType root = doc.root_container.first();
		// 
		// ...
		// doc.saveToFile("jbpm3processdocgpd1.xml", true);

	}

	public static void testInput() {
		try {
			com.jbpm3processdocgpd.jbpm3processdocgpd2 doc = com.jbpm3processdocgpd.jbpm3processdocgpd2.createDocument();
			//doc = com.jbpm3processdocgpd.jbpm3processdocgpd2.loadFromFile("D:/seamprojs/projs/jbpmmodel/src/main/com/jbpmmodel/bp/accountant_Fixed_Asset_Loss_Destruction_or_Theft/gpd.xml");
			doc = com.jbpm3processdocgpd.jbpm3processdocgpd2.loadFromFile("D:/seamprojs/projs/jbpmmodel/src/main/com/jbpmmodel/bp/dummy/gpd.xml");
			//D:/seamprojs/projs/jbpmmodel/src/main/com/jbpmmodel/bp/Document_Owner_Modifying_a_Process_Document/processdefinition.xml
			
            //dump xml string
            TransformerFactory transformerFactory;
            Transformer transformer;            
            transformerFactory = TransformerFactory.newInstance();
            transformer = transformerFactory.newTransformer();            
            DOMSource source = new DOMSource(doc.getNode());
            StringWriter buffer = new StringWriter(  );
            PrintWriter out = new PrintWriter(buffer);		
            javax.xml.transform.stream.StreamResult result = new javax.xml.transform.stream.StreamResult(out);
            transformer.transform(source, result);
            String results = buffer.toString(  );
            System.out.println("results\n" + results);            
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
	}
	
	
	public static void showJBPM3Doc() {
		try {
			com.jbpm3processdocgpd.jbpm3processdocgpd2 doc = com.jbpm3processdocgpd.jbpm3processdocgpd2.createDocument();
			doc = com.jbpm3processdocgpd.jbpm3processdocgpd2.loadFromFile("D:/seamprojs/projs/jbpmmodel/src/main/com/jbpmmodel/bp/accountant_Fixed_Asset_Loss_Destruction_or_Theft/gpd.xml");
            //dump xml string
            TransformerFactory transformerFactory;
            Transformer transformer;            
            transformerFactory = TransformerFactory.newInstance();
            transformer = transformerFactory.newTransformer();            
            DOMSource source = new DOMSource(doc.getNode());
            StringWriter buffer = new StringWriter(  );
            PrintWriter out = new PrintWriter(buffer);		
            javax.xml.transform.stream.StreamResult result = new javax.xml.transform.stream.StreamResult(out);
            transformer.transform(source, result);
            String results = buffer.toString(  );
            System.out.println("results\n" + results);            
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
	}
	
	public static void main(String args[]) {
		try {
			System.out.println("jbpm3processdocgpd Test Application");
			//example();
			showJBPM3Doc();
			System.out.println("OK");
			System.exit(0);
		} catch (Exception e) {
			e.printStackTrace();
			System.exit(1);
		}
	}
}
